version: "2"
run:
  go: "1.25"
  allow-parallel-runners: true
  timeout: 10m
  build-tags:
    - e2e  # Include e2e tests in linting
linters:
  default: none
  enable:
    # Code Quality
    - asasalint       # Detect []any in variadic args (e.g., misleading Printf calls)
    - asciicheck      # Find non-ASCII identifiers
    - copyloopvar     # Detect loop variable capture issues
    - dogsled         # Find excessive blank identifiers in assignments
    - dupl            # Detect duplicate code
    - dupword         # Find duplicated words in comments
    - durationcheck   # Detect incorrect time.Duration multiplication
    - errcheck        # Check for unchecked errors
    - errchkjson      # Check error handling of json encoding functions
    - goconst         # Find repeated strings that could be constants
    - gocritic        # Collection of opinionated linting checks
    - gocyclo         # Check cyclomatic complexity
    - godot           # Check that comments end with a period
    - goprintffuncname # Check printf-like function names end with f
    - govet           # Reports suspicious constructs
    - importas        # Enforce consistent import aliases
    - ineffassign     # Detect ineffective assignments
    - intrange        # Suggest integer range loops (Go 1.22+)
    - loggercheck     # Check logr/slog key-value pair consistency
    - nakedret        # Find naked returns in long functions
    - nolintlint      # Check nolint directives are well-formed and necessary
    - nosprintfhostport # Detect misuse of Sprintf for host:port
    - prealloc        # Find slice declarations that could be preallocated
    - predeclared     # Find shadowed predeclared identifiers
    - thelper         # Detect test helpers without t.Helper()
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Find unused function parameters
    - unused          # Find unused code

    # Static Analysis
    - staticcheck     # Comprehensive static analysis (includes gosimple and stylecheck)

    # Error Handling
    - errorlint       # Proper error wrapping and comparison
    - nilerr          # Check for nil error returns
    - nilnil          # Detect functions returning nil,nil

    # Security
    - gosec           # Security-oriented linting

    # Performance
    - bodyclose       # Check HTTP response body is closed
    - noctx           # Check for http requests without context

    # Code Style
    - lll             # Line length limit
    - misspell        # Find misspelled words
    - usestdlibvars   # Detect manual construction of stdlib vars/consts
    - whitespace      # Check for unnecessary whitespace

    # Testing
    - ginkgolinter    # Ginkgo/Gomega best practices
    - tparallel       # Detect improper t.Parallel() usage

    # Naming
    - revive          # Fast, configurable linter (replaces golint)

  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - appendAssign
        - commentedOutCode
        - hugeParam
        - rangeValCopy
        - regexpMust
    gocyclo:
      min-complexity: 20
    godot:
      scope: toplevel   # Only check top-level comments (exported symbols)
      exclude:
        - "SPDX-"       # Exclude SPDX license headers
        - "\\+kubebuilder"  # Exclude kubebuilder markers
        - "\\+groupName"    # Exclude kubebuilder group markers
    importas:
      no-unaliased: true
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/api/rbac/v1
          alias: rbacv1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
    lll:
      line-length: 180
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: constant-logical-expr
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: errorf
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
          disabled: true  # Too noisy for existing codebase
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: unused-parameter
          disabled: true  # Conflicts with interface compliance and callback signatures
        - name: var-naming
    gosec:
      excludes:
        - G104  # Unhandled errors (covered by errcheck)
        - G304  # File path from variable (intentional in some cases)

  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
        path: _test\.go$
      - linters:
          - dupl
        path: test/
      - linters:
          - lll
        path: internal/*
      - linters:
          - errcheck
        path: _test\.go$
      - linters:
          - gosec
        path: _test\.go$
      - linters:
          - gosec
        path: test/utils/
      - linters:
          - gosec
        path: test/e2e/
      - linters:
          - revive
        path: _test\.go$
        text: "dot-imports"
      - linters:
          - gocritic
        path: _test\.go$
      - linters:
          - godot
        path: _test\.go$
      - linters:
          - thelper
        path: _test\.go$
        text: "ginkgo"
      - linters:
          - gocyclo
        path: api/authorization/v1alpha1/binddefinition_webhook\.go$
      - linters:
          - gocyclo
        path: internal/controller/authorization/rolebinding_terminator_controller\.go$
      - linters:
          - gocyclo
        path: internal/webhook/authorization/namespace_validating_webhook\.go$
      - linters:
          - gocyclo
        path: internal/webhook/authorization/namespace_mutating_webhook_test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
