apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds/binddefinitions.authorization.t-caas.telekom.com.yaml
- crds/rbacpolicies.authorization.t-caas.telekom.com.yaml
- crds/restrictedbinddefinitions.authorization.t-caas.telekom.com.yaml
- crds/restrictedroledefinitions.authorization.t-caas.telekom.com.yaml
- crds/roledefinitions.authorization.t-caas.telekom.com.yaml
- crds/webhookauthorizers.authorization.t-caas.telekom.com.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: Delete=false
  helm.sh/resource-policy: keep
