# SPDX-FileCopyrightText: 2026 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: 'Build Operator Image'
description: 'Build the auth-operator Docker image with caching'

inputs:
  image-name:
    description: 'Name of the image to build'
    required: false
    default: 'auth-operator'
  image-tag:
    description: 'Tag for the image'
    required: false
    default: 'latest'
  push-to-registry:
    description: 'Push image to container registry'
    required: false
    default: 'false'
  registry:
    description: 'Container registry to push to (e.g., ghcr.io)'
    required: false
    default: 'ghcr.io'
  registry-username:
    description: 'Username for registry authentication'
    required: false
    default: ''
  registry-password:
    description: 'Password/token for registry authentication'
    required: false
    default: ''
  load-to-kind:
    description: 'Load image into kind cluster'
    required: false
    default: 'false'
  kind-cluster-name:
    description: 'Name of the kind cluster to load image into'
    required: false
    default: 'auth-operator-e2e'
  working-directory:
    description: 'Working directory containing the Dockerfile'
    required: false
    default: '.'

outputs:
  image:
    description: 'Full image reference (name:tag)'
    value: ${{ steps.build.outputs.image }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Log in to Container Registry
      if: inputs.push-to-registry == 'true'
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Build Docker image
      id: build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        IMAGE="${{ inputs.image-name }}:${{ inputs.image-tag }}"
        echo "Building image: $IMAGE"

        # Validate: cannot push to registry when loading to kind
        if [ "${{ inputs.push-to-registry }}" = "true" ] && [ "${{ inputs.load-to-kind }}" = "true" ]; then
          echo "ERROR: Cannot use push-to-registry and load-to-kind simultaneously"
          echo "load-to-kind requires the image to be available locally (--load), but push-to-registry uses --push"
          exit 1
        fi

        # Determine build flags based on push/load requirements
        BUILD_FLAGS=""
        if [ "${{ inputs.push-to-registry }}" = "true" ]; then
          BUILD_FLAGS="--push"
        else
          BUILD_FLAGS="--load"
        fi

        # Build with cache using buildx
        docker buildx build \
          --cache-from type=gha \
          --cache-to type=gha,mode=max \
          $BUILD_FLAGS \
          -t "$IMAGE" \
          .

        echo "image=$IMAGE" >> $GITHUB_OUTPUT

    - name: Load image into kind
      if: inputs.load-to-kind == 'true'
      shell: bash
      run: |
        kind load docker-image "${{ inputs.image-name }}:${{ inputs.image-tag }}" --name ${{ inputs.kind-cluster-name }}
