# SPDX-FileCopyrightText: 2026 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: auth-operator
    app.kubernetes.io/managed-by: kustomize
    authorization.t-caas.telekom.com/component: "webhook"
  name: webhook-server
  namespace: system
