/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BindingLimitsApplyConfiguration represents a declarative configuration of the BindingLimits type for use
// with apply.
//
// BindingLimits defines constraints on role bindings created by restricted definitions.
type BindingLimitsApplyConfiguration struct {
	// AllowClusterRoleBindings controls whether ClusterRoleBindings may be created.
	// Default is false (deny by default).
	AllowClusterRoleBindings *bool `json:"allowClusterRoleBindings,omitempty"`
	// ClusterRoleBindingLimits constrains which ClusterRoles may be referenced in CRBs.
	ClusterRoleBindingLimits *RoleRefLimitsApplyConfiguration `json:"clusterRoleBindingLimits,omitempty"`
	// RoleBindingLimits constrains which ClusterRoles/Roles may be referenced in RBs.
	RoleBindingLimits *RoleRefLimitsApplyConfiguration `json:"roleBindingLimits,omitempty"`
	// TargetNamespaceLimits constrains which namespaces may be targeted.
	TargetNamespaceLimits *NamespaceLimitsApplyConfiguration `json:"targetNamespaceLimits,omitempty"`
}

// BindingLimitsApplyConfiguration constructs a declarative configuration of the BindingLimits type for use with
// apply.
func BindingLimits() *BindingLimitsApplyConfiguration {
	return &BindingLimitsApplyConfiguration{}
}

// WithAllowClusterRoleBindings sets the AllowClusterRoleBindings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowClusterRoleBindings field is set to the value of the last call.
func (b *BindingLimitsApplyConfiguration) WithAllowClusterRoleBindings(value bool) *BindingLimitsApplyConfiguration {
	b.AllowClusterRoleBindings = &value
	return b
}

// WithClusterRoleBindingLimits sets the ClusterRoleBindingLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRoleBindingLimits field is set to the value of the last call.
func (b *BindingLimitsApplyConfiguration) WithClusterRoleBindingLimits(value *RoleRefLimitsApplyConfiguration) *BindingLimitsApplyConfiguration {
	b.ClusterRoleBindingLimits = value
	return b
}

// WithRoleBindingLimits sets the RoleBindingLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleBindingLimits field is set to the value of the last call.
func (b *BindingLimitsApplyConfiguration) WithRoleBindingLimits(value *RoleRefLimitsApplyConfiguration) *BindingLimitsApplyConfiguration {
	b.RoleBindingLimits = value
	return b
}

// WithTargetNamespaceLimits sets the TargetNamespaceLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetNamespaceLimits field is set to the value of the last call.
func (b *BindingLimitsApplyConfiguration) WithTargetNamespaceLimits(value *NamespaceLimitsApplyConfiguration) *BindingLimitsApplyConfiguration {
	b.TargetNamespaceLimits = value
	return b
}
