/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/rbac/v1"
)

// BindDefinitionSpecApplyConfiguration represents a declarative configuration of the BindDefinitionSpec type for use
// with apply.
//
// BindDefinitionSpec defines the desired state of BindDefinition.
type BindDefinitionSpecApplyConfiguration struct {
	// Name that will be prefixed to the concatenated string which is the name of the binding. Follows format "targetName-clusterrole/role-binding" where clusterrole/role is the in-cluster existing ClusterRole or Role.
	TargetName *string `json:"targetName,omitempty"`
	// List of subjects that will be bound to a target ClusterRole/Role. Can be "User", "Group" or "ServiceAccount".
	Subjects []v1.Subject `json:"subjects,omitempty"`
	// List of ClusterRoles to which subjects will be bound to. The list is a RoleRef which means we have to specify the full rbacv1.RoleRef schema. The result of specifying this field are ClusterRoleBindings.
	ClusterRoleBindings *ClusterBindingApplyConfiguration `json:"clusterRoleBindings,omitempty"`
	// List of ClusterRoles/Roles to which subjects will be bound to. The list is a RoleRef which means we have to specify the full rbacv1.RoleRef schema. The result of specifying the field are RoleBindings.
	RoleBindings []NamespaceBindingApplyConfiguration `json:"roleBindings,omitempty"`
	// AutomountServiceAccountToken controls whether to automount API credentials for ServiceAccounts
	// created by this BindDefinition. Defaults to true for backward compatibility with Kubernetes
	// native ServiceAccount behavior. Set to false to improve security by preventing automatic
	// token mounting.
	// Only applies when Subjects contain ServiceAccount entries that need to be auto-created.
	AutomountServiceAccountToken *bool `json:"automountServiceAccountToken,omitempty"`
}

// BindDefinitionSpecApplyConfiguration constructs a declarative configuration of the BindDefinitionSpec type for use with
// apply.
func BindDefinitionSpec() *BindDefinitionSpecApplyConfiguration {
	return &BindDefinitionSpecApplyConfiguration{}
}

// WithTargetName sets the TargetName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetName field is set to the value of the last call.
func (b *BindDefinitionSpecApplyConfiguration) WithTargetName(value string) *BindDefinitionSpecApplyConfiguration {
	b.TargetName = &value
	return b
}

// WithSubjects adds the given value to the Subjects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subjects field.
func (b *BindDefinitionSpecApplyConfiguration) WithSubjects(values ...v1.Subject) *BindDefinitionSpecApplyConfiguration {
	for i := range values {
		b.Subjects = append(b.Subjects, values[i])
	}
	return b
}

// WithClusterRoleBindings sets the ClusterRoleBindings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRoleBindings field is set to the value of the last call.
func (b *BindDefinitionSpecApplyConfiguration) WithClusterRoleBindings(value *ClusterBindingApplyConfiguration) *BindDefinitionSpecApplyConfiguration {
	b.ClusterRoleBindings = value
	return b
}

// WithRoleBindings adds the given value to the RoleBindings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RoleBindings field.
func (b *BindDefinitionSpecApplyConfiguration) WithRoleBindings(values ...*NamespaceBindingApplyConfiguration) *BindDefinitionSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoleBindings")
		}
		b.RoleBindings = append(b.RoleBindings, *values[i])
	}
	return b
}

// WithAutomountServiceAccountToken sets the AutomountServiceAccountToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutomountServiceAccountToken field is set to the value of the last call.
func (b *BindDefinitionSpecApplyConfiguration) WithAutomountServiceAccountToken(value bool) *BindDefinitionSpecApplyConfiguration {
	b.AutomountServiceAccountToken = &value
	return b
}
