/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BindDefinitionStatusApplyConfiguration represents a declarative configuration of the BindDefinitionStatus type for use
// with apply.
//
// BindDefinitionStatus defines the observed state of BindDefinition.
type BindDefinitionStatusApplyConfiguration struct {
	// ObservedGeneration is the last observed generation of the resource.
	// This is used by kstatus to determine if the resource is current.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Not extremely important as most status updates are driven by Conditions. We read the JSONPath from this status field to signify completed reconciliation.
	BindReconciled *bool `json:"bindReconciled,omitempty"`
	// If the BindDefinition points to a subject of "Kind: ServiceAccount" and the service account is not present. The controller will reconcile it automatically.
	GeneratedServiceAccounts []v1.Subject `json:"generatedServiceAccounts,omitempty"`
	// Conditions defines current service state of the Bind definition. All conditions should evaluate to true to signify successful reconciliation.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// BindDefinitionStatusApplyConfiguration constructs a declarative configuration of the BindDefinitionStatus type for use with
// apply.
func BindDefinitionStatus() *BindDefinitionStatusApplyConfiguration {
	return &BindDefinitionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BindDefinitionStatusApplyConfiguration) WithObservedGeneration(value int64) *BindDefinitionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithBindReconciled sets the BindReconciled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BindReconciled field is set to the value of the last call.
func (b *BindDefinitionStatusApplyConfiguration) WithBindReconciled(value bool) *BindDefinitionStatusApplyConfiguration {
	b.BindReconciled = &value
	return b
}

// WithGeneratedServiceAccounts adds the given value to the GeneratedServiceAccounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the GeneratedServiceAccounts field.
func (b *BindDefinitionStatusApplyConfiguration) WithGeneratedServiceAccounts(values ...v1.Subject) *BindDefinitionStatusApplyConfiguration {
	for i := range values {
		b.GeneratedServiceAccounts = append(b.GeneratedServiceAccounts, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BindDefinitionStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *BindDefinitionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
