/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ClusterBindingApplyConfiguration represents a declarative configuration of the ClusterBinding type for use
// with apply.
//
// ClusterBinding defines cluster-scoped role bindings.
type ClusterBindingApplyConfiguration struct {
	// ClusterRoleRefs references an existing ClusterRole
	ClusterRoleRefs []string `json:"clusterRoleRefs,omitempty"`
}

// ClusterBindingApplyConfiguration constructs a declarative configuration of the ClusterBinding type for use with
// apply.
func ClusterBinding() *ClusterBindingApplyConfiguration {
	return &ClusterBindingApplyConfiguration{}
}

// WithClusterRoleRefs adds the given value to the ClusterRoleRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ClusterRoleRefs field.
func (b *ClusterBindingApplyConfiguration) WithClusterRoleRefs(values ...string) *ClusterBindingApplyConfiguration {
	for i := range values {
		b.ClusterRoleRefs = append(b.ClusterRoleRefs, values[i])
	}
	return b
}
