/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DefaultPolicyAssignmentApplyConfiguration represents a declarative configuration of the DefaultPolicyAssignment type for use
// with apply.
//
// DefaultPolicyAssignment defines identities that must use this policy by default
// when creating RestrictedBindDefinition/RestrictedRoleDefinition resources.
type DefaultPolicyAssignmentApplyConfiguration struct {
	// Groups lists requester group names for which this policy is the default.
	Groups []string `json:"groups,omitempty"`
	// ServiceAccounts lists requester ServiceAccounts for which this policy is the default.
	ServiceAccounts []SARefApplyConfiguration `json:"serviceAccounts,omitempty"`
}

// DefaultPolicyAssignmentApplyConfiguration constructs a declarative configuration of the DefaultPolicyAssignment type for use with
// apply.
func DefaultPolicyAssignment() *DefaultPolicyAssignmentApplyConfiguration {
	return &DefaultPolicyAssignmentApplyConfiguration{}
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *DefaultPolicyAssignmentApplyConfiguration) WithGroups(values ...string) *DefaultPolicyAssignmentApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}

// WithServiceAccounts adds the given value to the ServiceAccounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ServiceAccounts field.
func (b *DefaultPolicyAssignmentApplyConfiguration) WithServiceAccounts(values ...*SARefApplyConfiguration) *DefaultPolicyAssignmentApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithServiceAccounts")
		}
		b.ServiceAccounts = append(b.ServiceAccounts, *values[i])
	}
	return b
}
