/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ImpersonationConfigApplyConfiguration represents a declarative configuration of the ImpersonationConfig type for use
// with apply.
//
// ImpersonationConfig controls apply-time ServiceAccount impersonation for
// RestrictedBindDefinition and RestrictedRoleDefinition reconciliation.
type ImpersonationConfigApplyConfiguration struct {
	// Enabled enables ServiceAccount impersonation during restricted resource apply operations.
	Enabled *bool `json:"enabled,omitempty"`
	// ServiceAccountRef is the ServiceAccount identity used for impersonated apply operations.
	// Required when enabled is true.
	ServiceAccountRef *SARefApplyConfiguration `json:"serviceAccountRef,omitempty"`
}

// ImpersonationConfigApplyConfiguration constructs a declarative configuration of the ImpersonationConfig type for use with
// apply.
func ImpersonationConfig() *ImpersonationConfigApplyConfiguration {
	return &ImpersonationConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ImpersonationConfigApplyConfiguration) WithEnabled(value bool) *ImpersonationConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithServiceAccountRef sets the ServiceAccountRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountRef field is set to the value of the last call.
func (b *ImpersonationConfigApplyConfiguration) WithServiceAccountRef(value *SARefApplyConfiguration) *ImpersonationConfigApplyConfiguration {
	b.ServiceAccountRef = value
	return b
}
