/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// NamespaceLimitsApplyConfiguration represents a declarative configuration of the NamespaceLimits type for use
// with apply.
//
// NamespaceLimits controls which namespaces can be targeted by bindings.
type NamespaceLimitsApplyConfiguration struct {
	// AllowedNamespaceSelector selects allowed namespaces by label.
	AllowedNamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"allowedNamespaceSelector,omitempty"`
	// ForbiddenNamespaces is a list of namespace names that may not be targeted.
	ForbiddenNamespaces []string `json:"forbiddenNamespaces,omitempty"`
	// ForbiddenNamespacePrefixes is a list of namespace name prefixes that may not be targeted.
	ForbiddenNamespacePrefixes []string `json:"forbiddenNamespacePrefixes,omitempty"`
	// MaxTargetNamespaces limits the number of target namespaces per binding.
	MaxTargetNamespaces *int32 `json:"maxTargetNamespaces,omitempty"`
}

// NamespaceLimitsApplyConfiguration constructs a declarative configuration of the NamespaceLimits type for use with
// apply.
func NamespaceLimits() *NamespaceLimitsApplyConfiguration {
	return &NamespaceLimitsApplyConfiguration{}
}

// WithAllowedNamespaceSelector sets the AllowedNamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowedNamespaceSelector field is set to the value of the last call.
func (b *NamespaceLimitsApplyConfiguration) WithAllowedNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *NamespaceLimitsApplyConfiguration {
	b.AllowedNamespaceSelector = value
	return b
}

// WithForbiddenNamespaces adds the given value to the ForbiddenNamespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenNamespaces field.
func (b *NamespaceLimitsApplyConfiguration) WithForbiddenNamespaces(values ...string) *NamespaceLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenNamespaces = append(b.ForbiddenNamespaces, values[i])
	}
	return b
}

// WithForbiddenNamespacePrefixes adds the given value to the ForbiddenNamespacePrefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenNamespacePrefixes field.
func (b *NamespaceLimitsApplyConfiguration) WithForbiddenNamespacePrefixes(values ...string) *NamespaceLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenNamespacePrefixes = append(b.ForbiddenNamespacePrefixes, values[i])
	}
	return b
}

// WithMaxTargetNamespaces sets the MaxTargetNamespaces field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxTargetNamespaces field is set to the value of the last call.
func (b *NamespaceLimitsApplyConfiguration) WithMaxTargetNamespaces(value int32) *NamespaceLimitsApplyConfiguration {
	b.MaxTargetNamespaces = &value
	return b
}
