/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// NamespaceBindingApplyConfiguration represents a declarative configuration of the NamespaceBinding type for use
// with apply.
//
// NamespaceBinding defines namespace-scoped role bindings.
type NamespaceBindingApplyConfiguration struct {
	// ClusterRoleRefs references an existing ClusterRole
	ClusterRoleRefs []string `json:"clusterRoleRefs,omitempty"`
	// RoleRefs references a specific Role that has to exist in the target namespaces
	RoleRefs []string `json:"roleRefs,omitempty"`
	// Namespace of the Role that should be bound to the subjects.
	Namespace *string `json:"namespace,omitempty"`
	// NamespaceSelector is a label selector which will match namespaces that should have the RoleBinding/s.
	NamespaceSelector []v1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
}

// NamespaceBindingApplyConfiguration constructs a declarative configuration of the NamespaceBinding type for use with
// apply.
func NamespaceBinding() *NamespaceBindingApplyConfiguration {
	return &NamespaceBindingApplyConfiguration{}
}

// WithClusterRoleRefs adds the given value to the ClusterRoleRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ClusterRoleRefs field.
func (b *NamespaceBindingApplyConfiguration) WithClusterRoleRefs(values ...string) *NamespaceBindingApplyConfiguration {
	for i := range values {
		b.ClusterRoleRefs = append(b.ClusterRoleRefs, values[i])
	}
	return b
}

// WithRoleRefs adds the given value to the RoleRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RoleRefs field.
func (b *NamespaceBindingApplyConfiguration) WithRoleRefs(values ...string) *NamespaceBindingApplyConfiguration {
	for i := range values {
		b.RoleRefs = append(b.RoleRefs, values[i])
	}
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *NamespaceBindingApplyConfiguration) WithNamespace(value string) *NamespaceBindingApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithNamespaceSelector adds the given value to the NamespaceSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NamespaceSelector field.
func (b *NamespaceBindingApplyConfiguration) WithNamespaceSelector(values ...*v1.LabelSelectorApplyConfiguration) *NamespaceBindingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNamespaceSelector")
		}
		b.NamespaceSelector = append(b.NamespaceSelector, *values[i])
	}
	return b
}
