/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NameMatchLimitsApplyConfiguration represents a declarative configuration of the NameMatchLimits type for use
// with apply.
//
// NameMatchLimits defines name-based allow/deny patterns for subjects.
type NameMatchLimitsApplyConfiguration struct {
	// AllowedNames is a list of allowed subject names.
	AllowedNames []string `json:"allowedNames,omitempty"`
	// ForbiddenNames is a list of forbidden subject names.
	ForbiddenNames []string `json:"forbiddenNames,omitempty"`
	// AllowedPrefixes is a list of allowed name prefixes.
	AllowedPrefixes []string `json:"allowedPrefixes,omitempty"`
	// ForbiddenPrefixes is a list of forbidden name prefixes.
	ForbiddenPrefixes []string `json:"forbiddenPrefixes,omitempty"`
	// AllowedSuffixes is a list of allowed name suffixes.
	AllowedSuffixes []string `json:"allowedSuffixes,omitempty"`
	// ForbiddenSuffixes is a list of forbidden name suffixes.
	ForbiddenSuffixes []string `json:"forbiddenSuffixes,omitempty"`
}

// NameMatchLimitsApplyConfiguration constructs a declarative configuration of the NameMatchLimits type for use with
// apply.
func NameMatchLimits() *NameMatchLimitsApplyConfiguration {
	return &NameMatchLimitsApplyConfiguration{}
}

// WithAllowedNames adds the given value to the AllowedNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedNames field.
func (b *NameMatchLimitsApplyConfiguration) WithAllowedNames(values ...string) *NameMatchLimitsApplyConfiguration {
	for i := range values {
		b.AllowedNames = append(b.AllowedNames, values[i])
	}
	return b
}

// WithForbiddenNames adds the given value to the ForbiddenNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenNames field.
func (b *NameMatchLimitsApplyConfiguration) WithForbiddenNames(values ...string) *NameMatchLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenNames = append(b.ForbiddenNames, values[i])
	}
	return b
}

// WithAllowedPrefixes adds the given value to the AllowedPrefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedPrefixes field.
func (b *NameMatchLimitsApplyConfiguration) WithAllowedPrefixes(values ...string) *NameMatchLimitsApplyConfiguration {
	for i := range values {
		b.AllowedPrefixes = append(b.AllowedPrefixes, values[i])
	}
	return b
}

// WithForbiddenPrefixes adds the given value to the ForbiddenPrefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenPrefixes field.
func (b *NameMatchLimitsApplyConfiguration) WithForbiddenPrefixes(values ...string) *NameMatchLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenPrefixes = append(b.ForbiddenPrefixes, values[i])
	}
	return b
}

// WithAllowedSuffixes adds the given value to the AllowedSuffixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedSuffixes field.
func (b *NameMatchLimitsApplyConfiguration) WithAllowedSuffixes(values ...string) *NameMatchLimitsApplyConfiguration {
	for i := range values {
		b.AllowedSuffixes = append(b.AllowedSuffixes, values[i])
	}
	return b
}

// WithForbiddenSuffixes adds the given value to the ForbiddenSuffixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenSuffixes field.
func (b *NameMatchLimitsApplyConfiguration) WithForbiddenSuffixes(values ...string) *NameMatchLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenSuffixes = append(b.ForbiddenSuffixes, values[i])
	}
	return b
}
