/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PolicyScopeApplyConfiguration represents a declarative configuration of the PolicyScope type for use
// with apply.
//
// PolicyScope defines which namespaces this policy governs.
type PolicyScopeApplyConfiguration struct {
	// NamespaceSelector selects namespaces by label selector.
	NamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
	// Namespaces is an explicit list of namespace names.
	Namespaces []string `json:"namespaces,omitempty"`
}

// PolicyScopeApplyConfiguration constructs a declarative configuration of the PolicyScope type for use with
// apply.
func PolicyScope() *PolicyScopeApplyConfiguration {
	return &PolicyScopeApplyConfiguration{}
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *PolicyScopeApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *PolicyScopeApplyConfiguration {
	b.NamespaceSelector = value
	return b
}

// WithNamespaces adds the given value to the Namespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Namespaces field.
func (b *PolicyScopeApplyConfiguration) WithNamespaces(values ...string) *PolicyScopeApplyConfiguration {
	for i := range values {
		b.Namespaces = append(b.Namespaces, values[i])
	}
	return b
}
