/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RBACPolicySpecApplyConfiguration represents a declarative configuration of the RBACPolicySpec type for use
// with apply.
//
// RBACPolicySpec defines the desired state of RBACPolicy.
type RBACPolicySpecApplyConfiguration struct {
	// AppliesTo defines the namespace scope this policy governs.
	AppliesTo *PolicyScopeApplyConfiguration `json:"appliesTo,omitempty"`
	// BindingLimits constrains role bindings that may be created.
	BindingLimits *BindingLimitsApplyConfiguration `json:"bindingLimits,omitempty"`
	// RoleLimits constrains roles that may be generated.
	RoleLimits *RoleLimitsApplyConfiguration `json:"roleLimits,omitempty"`
	// SubjectLimits constrains the subjects a tenant may use.
	SubjectLimits *SubjectLimitsApplyConfiguration `json:"subjectLimits,omitempty"`
}

// RBACPolicySpecApplyConfiguration constructs a declarative configuration of the RBACPolicySpec type for use with
// apply.
func RBACPolicySpec() *RBACPolicySpecApplyConfiguration {
	return &RBACPolicySpecApplyConfiguration{}
}

// WithAppliesTo sets the AppliesTo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppliesTo field is set to the value of the last call.
func (b *RBACPolicySpecApplyConfiguration) WithAppliesTo(value *PolicyScopeApplyConfiguration) *RBACPolicySpecApplyConfiguration {
	b.AppliesTo = value
	return b
}

// WithBindingLimits sets the BindingLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BindingLimits field is set to the value of the last call.
func (b *RBACPolicySpecApplyConfiguration) WithBindingLimits(value *BindingLimitsApplyConfiguration) *RBACPolicySpecApplyConfiguration {
	b.BindingLimits = value
	return b
}

// WithRoleLimits sets the RoleLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleLimits field is set to the value of the last call.
func (b *RBACPolicySpecApplyConfiguration) WithRoleLimits(value *RoleLimitsApplyConfiguration) *RBACPolicySpecApplyConfiguration {
	b.RoleLimits = value
	return b
}

// WithSubjectLimits sets the SubjectLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubjectLimits field is set to the value of the last call.
func (b *RBACPolicySpecApplyConfiguration) WithSubjectLimits(value *SubjectLimitsApplyConfiguration) *RBACPolicySpecApplyConfiguration {
	b.SubjectLimits = value
	return b
}
