/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RBACPolicyStatusApplyConfiguration represents a declarative configuration of the RBACPolicyStatus type for use
// with apply.
//
// RBACPolicyStatus defines the observed state of RBACPolicy.
type RBACPolicyStatusApplyConfiguration struct {
	// ObservedGeneration is the last observed generation of the resource.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// BoundResourceCount is the number of RestrictedBindDefinitions and
	// RestrictedRoleDefinitions currently referencing this policy.
	BoundResourceCount *int32 `json:"boundResourceCount,omitempty"`
	// Conditions defines current service state of the RBACPolicy.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// RBACPolicyStatusApplyConfiguration constructs a declarative configuration of the RBACPolicyStatus type for use with
// apply.
func RBACPolicyStatus() *RBACPolicyStatusApplyConfiguration {
	return &RBACPolicyStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *RBACPolicyStatusApplyConfiguration) WithObservedGeneration(value int64) *RBACPolicyStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithBoundResourceCount sets the BoundResourceCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BoundResourceCount field is set to the value of the last call.
func (b *RBACPolicyStatusApplyConfiguration) WithBoundResourceCount(value int32) *RBACPolicyStatusApplyConfiguration {
	b.BoundResourceCount = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RBACPolicyStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *RBACPolicyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
