/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ResourceVerbRuleApplyConfiguration represents a declarative configuration of the ResourceVerbRule type for use
// with apply.
//
// ResourceVerbRule specifies a forbidden combination of resource, API group, and verbs.
type ResourceVerbRuleApplyConfiguration struct {
	// Resource is the resource name (e.g., "pods", "secrets").
	Resource *string `json:"resource,omitempty"`
	// APIGroup is the API group of the resource. Empty string means core group.
	APIGroup *string `json:"apiGroup,omitempty"`
	// Verbs are the verbs forbidden on this resource.
	Verbs []string `json:"verbs,omitempty"`
}

// ResourceVerbRuleApplyConfiguration constructs a declarative configuration of the ResourceVerbRule type for use with
// apply.
func ResourceVerbRule() *ResourceVerbRuleApplyConfiguration {
	return &ResourceVerbRuleApplyConfiguration{}
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ResourceVerbRuleApplyConfiguration) WithResource(value string) *ResourceVerbRuleApplyConfiguration {
	b.Resource = &value
	return b
}

// WithAPIGroup sets the APIGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIGroup field is set to the value of the last call.
func (b *ResourceVerbRuleApplyConfiguration) WithAPIGroup(value string) *ResourceVerbRuleApplyConfiguration {
	b.APIGroup = &value
	return b
}

// WithVerbs adds the given value to the Verbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Verbs field.
func (b *ResourceVerbRuleApplyConfiguration) WithVerbs(values ...string) *ResourceVerbRuleApplyConfiguration {
	for i := range values {
		b.Verbs = append(b.Verbs, values[i])
	}
	return b
}
