/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RestrictedBindDefinitionStatusApplyConfiguration represents a declarative configuration of the RestrictedBindDefinitionStatus type for use
// with apply.
//
// RestrictedBindDefinitionStatus defines the observed state of RestrictedBindDefinition.
type RestrictedBindDefinitionStatusApplyConfiguration struct {
	// ObservedGeneration is the last observed generation of the resource.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// BindReconciled indicates whether bindings have been successfully reconciled.
	BindReconciled *bool `json:"bindReconciled,omitempty"`
	// GeneratedServiceAccounts lists ServiceAccounts that were auto-created.
	GeneratedServiceAccounts []v1.Subject `json:"generatedServiceAccounts,omitempty"`
	// MissingRoleRefs lists role references that could not be resolved.
	// Format: "ClusterRole/<name>" or "Role/<namespace>/<name>".
	MissingRoleRefs []string `json:"missingRoleRefs,omitempty"`
	// ExternalServiceAccounts lists ServiceAccounts referenced by this RestrictedBindDefinition
	// that were not created by the controller.
	// Format: "<namespace>/<name>".
	ExternalServiceAccounts []string `json:"externalServiceAccounts,omitempty"`
	// PolicyViolations lists policy violations detected during the last reconciliation.
	// Format: "<fieldPath>: <message>" when a field path is available.
	// Empty when all checks pass.
	PolicyViolations []string `json:"policyViolations,omitempty"`
	// Conditions defines current service state.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// RestrictedBindDefinitionStatusApplyConfiguration constructs a declarative configuration of the RestrictedBindDefinitionStatus type for use with
// apply.
func RestrictedBindDefinitionStatus() *RestrictedBindDefinitionStatusApplyConfiguration {
	return &RestrictedBindDefinitionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *RestrictedBindDefinitionStatusApplyConfiguration) WithObservedGeneration(value int64) *RestrictedBindDefinitionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithBindReconciled sets the BindReconciled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BindReconciled field is set to the value of the last call.
func (b *RestrictedBindDefinitionStatusApplyConfiguration) WithBindReconciled(value bool) *RestrictedBindDefinitionStatusApplyConfiguration {
	b.BindReconciled = &value
	return b
}

// WithGeneratedServiceAccounts adds the given value to the GeneratedServiceAccounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the GeneratedServiceAccounts field.
func (b *RestrictedBindDefinitionStatusApplyConfiguration) WithGeneratedServiceAccounts(values ...v1.Subject) *RestrictedBindDefinitionStatusApplyConfiguration {
	for i := range values {
		b.GeneratedServiceAccounts = append(b.GeneratedServiceAccounts, values[i])
	}
	return b
}

// WithMissingRoleRefs adds the given value to the MissingRoleRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MissingRoleRefs field.
func (b *RestrictedBindDefinitionStatusApplyConfiguration) WithMissingRoleRefs(values ...string) *RestrictedBindDefinitionStatusApplyConfiguration {
	for i := range values {
		b.MissingRoleRefs = append(b.MissingRoleRefs, values[i])
	}
	return b
}

// WithExternalServiceAccounts adds the given value to the ExternalServiceAccounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExternalServiceAccounts field.
func (b *RestrictedBindDefinitionStatusApplyConfiguration) WithExternalServiceAccounts(values ...string) *RestrictedBindDefinitionStatusApplyConfiguration {
	for i := range values {
		b.ExternalServiceAccounts = append(b.ExternalServiceAccounts, values[i])
	}
	return b
}

// WithPolicyViolations adds the given value to the PolicyViolations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PolicyViolations field.
func (b *RestrictedBindDefinitionStatusApplyConfiguration) WithPolicyViolations(values ...string) *RestrictedBindDefinitionStatusApplyConfiguration {
	for i := range values {
		b.PolicyViolations = append(b.PolicyViolations, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RestrictedBindDefinitionStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *RestrictedBindDefinitionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
