/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/rbac/v1"
)

// RestrictedBindDefinitionSpecApplyConfiguration represents a declarative configuration of the RestrictedBindDefinitionSpec type for use
// with apply.
//
// RestrictedBindDefinitionSpec defines the desired state of RestrictedBindDefinition.
type RestrictedBindDefinitionSpecApplyConfiguration struct {
	// PolicyRef references the RBACPolicy that governs this binding.
	// This field is immutable after creation.
	PolicyRef *RBACPolicyReferenceApplyConfiguration `json:"policyRef,omitempty"`
	// TargetName is the name prefix for generated bindings. Follows format
	// "targetName-clusterrole/role-binding".
	// This field is immutable after creation.
	TargetName *string `json:"targetName,omitempty"`
	// Subjects lists the subjects that will be bound to the target ClusterRole/Role.
	// Can be "User", "Group" or "ServiceAccount".
	Subjects []v1.Subject `json:"subjects,omitempty"`
	// ClusterRoleBindings defines cluster-scoped role bindings.
	ClusterRoleBindings *ClusterBindingApplyConfiguration `json:"clusterRoleBindings,omitempty"`
	// RoleBindings defines namespace-scoped role bindings.
	RoleBindings []NamespaceBindingApplyConfiguration `json:"roleBindings,omitempty"`
	// AutomountServiceAccountToken controls whether to automount API credentials
	// for ServiceAccounts created by this RestrictedBindDefinition.
	AutomountServiceAccountToken *bool `json:"automountServiceAccountToken,omitempty"`
}

// RestrictedBindDefinitionSpecApplyConfiguration constructs a declarative configuration of the RestrictedBindDefinitionSpec type for use with
// apply.
func RestrictedBindDefinitionSpec() *RestrictedBindDefinitionSpecApplyConfiguration {
	return &RestrictedBindDefinitionSpecApplyConfiguration{}
}

// WithPolicyRef sets the PolicyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PolicyRef field is set to the value of the last call.
func (b *RestrictedBindDefinitionSpecApplyConfiguration) WithPolicyRef(value *RBACPolicyReferenceApplyConfiguration) *RestrictedBindDefinitionSpecApplyConfiguration {
	b.PolicyRef = value
	return b
}

// WithTargetName sets the TargetName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetName field is set to the value of the last call.
func (b *RestrictedBindDefinitionSpecApplyConfiguration) WithTargetName(value string) *RestrictedBindDefinitionSpecApplyConfiguration {
	b.TargetName = &value
	return b
}

// WithSubjects adds the given value to the Subjects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subjects field.
func (b *RestrictedBindDefinitionSpecApplyConfiguration) WithSubjects(values ...v1.Subject) *RestrictedBindDefinitionSpecApplyConfiguration {
	for i := range values {
		b.Subjects = append(b.Subjects, values[i])
	}
	return b
}

// WithClusterRoleBindings sets the ClusterRoleBindings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRoleBindings field is set to the value of the last call.
func (b *RestrictedBindDefinitionSpecApplyConfiguration) WithClusterRoleBindings(value *ClusterBindingApplyConfiguration) *RestrictedBindDefinitionSpecApplyConfiguration {
	b.ClusterRoleBindings = value
	return b
}

// WithRoleBindings adds the given value to the RoleBindings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RoleBindings field.
func (b *RestrictedBindDefinitionSpecApplyConfiguration) WithRoleBindings(values ...*NamespaceBindingApplyConfiguration) *RestrictedBindDefinitionSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoleBindings")
		}
		b.RoleBindings = append(b.RoleBindings, *values[i])
	}
	return b
}

// WithAutomountServiceAccountToken sets the AutomountServiceAccountToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutomountServiceAccountToken field is set to the value of the last call.
func (b *RestrictedBindDefinitionSpecApplyConfiguration) WithAutomountServiceAccountToken(value bool) *RestrictedBindDefinitionSpecApplyConfiguration {
	b.AutomountServiceAccountToken = &value
	return b
}
