/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RestrictedRoleDefinitionStatusApplyConfiguration represents a declarative configuration of the RestrictedRoleDefinitionStatus type for use
// with apply.
//
// RestrictedRoleDefinitionStatus defines the observed state of RestrictedRoleDefinition.
type RestrictedRoleDefinitionStatusApplyConfiguration struct {
	// ObservedGeneration is the last observed generation of the resource.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// RoleReconciled indicates whether the target role has been successfully reconciled.
	RoleReconciled *bool `json:"roleReconciled,omitempty"`
	// PolicyViolations lists policy violations detected during the last reconciliation.
	PolicyViolations []string `json:"policyViolations,omitempty"`
	// Conditions defines current service state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// RestrictedRoleDefinitionStatusApplyConfiguration constructs a declarative configuration of the RestrictedRoleDefinitionStatus type for use with
// apply.
func RestrictedRoleDefinitionStatus() *RestrictedRoleDefinitionStatusApplyConfiguration {
	return &RestrictedRoleDefinitionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *RestrictedRoleDefinitionStatusApplyConfiguration) WithObservedGeneration(value int64) *RestrictedRoleDefinitionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithRoleReconciled sets the RoleReconciled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleReconciled field is set to the value of the last call.
func (b *RestrictedRoleDefinitionStatusApplyConfiguration) WithRoleReconciled(value bool) *RestrictedRoleDefinitionStatusApplyConfiguration {
	b.RoleReconciled = &value
	return b
}

// WithPolicyViolations adds the given value to the PolicyViolations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PolicyViolations field.
func (b *RestrictedRoleDefinitionStatusApplyConfiguration) WithPolicyViolations(values ...string) *RestrictedRoleDefinitionStatusApplyConfiguration {
	for i := range values {
		b.PolicyViolations = append(b.PolicyViolations, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RestrictedRoleDefinitionStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *RestrictedRoleDefinitionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
