/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RestrictedRoleDefinitionSpecApplyConfiguration represents a declarative configuration of the RestrictedRoleDefinitionSpec type for use
// with apply.
//
// RestrictedRoleDefinitionSpec defines the desired state of RestrictedRoleDefinition.
type RestrictedRoleDefinitionSpecApplyConfiguration struct {
	// PolicyRef references the RBACPolicy that governs this role definition.
	// This field is immutable after creation.
	PolicyRef *RBACPolicyReferenceApplyConfiguration `json:"policyRef,omitempty"`
	// TargetRole is the role type that will be reconciled: ClusterRole or Role.
	// This field is immutable after creation.
	TargetRole *string `json:"targetRole,omitempty"`
	// TargetName is the name of the target role.
	// This field is immutable after creation.
	TargetName *string `json:"targetName,omitempty"`
	// TargetNamespace is the target namespace for the Role.
	// Required when "TargetRole" is "Role".
	TargetNamespace *string `json:"targetNamespace,omitempty"`
	// ScopeNamespaced controls whether the API resource filter includes
	// namespaced or cluster-scoped resources.
	ScopeNamespaced *bool `json:"scopeNamespaced,omitempty"`
	// RestrictedAPIs holds API groups which will NOT be included in the generated role.
	RestrictedAPIs []v1.APIGroup `json:"restrictedApis,omitempty"`
	// RestrictedResources holds resources which will NOT be included in the generated role.
	RestrictedResources []v1.APIResource `json:"restrictedResources,omitempty"`
	// RestrictedVerbs holds verbs which will NOT be included in the generated role.
	RestrictedVerbs []string `json:"restrictedVerbs,omitempty"`
}

// RestrictedRoleDefinitionSpecApplyConfiguration constructs a declarative configuration of the RestrictedRoleDefinitionSpec type for use with
// apply.
func RestrictedRoleDefinitionSpec() *RestrictedRoleDefinitionSpecApplyConfiguration {
	return &RestrictedRoleDefinitionSpecApplyConfiguration{}
}

// WithPolicyRef sets the PolicyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PolicyRef field is set to the value of the last call.
func (b *RestrictedRoleDefinitionSpecApplyConfiguration) WithPolicyRef(value *RBACPolicyReferenceApplyConfiguration) *RestrictedRoleDefinitionSpecApplyConfiguration {
	b.PolicyRef = value
	return b
}

// WithTargetRole sets the TargetRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetRole field is set to the value of the last call.
func (b *RestrictedRoleDefinitionSpecApplyConfiguration) WithTargetRole(value string) *RestrictedRoleDefinitionSpecApplyConfiguration {
	b.TargetRole = &value
	return b
}

// WithTargetName sets the TargetName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetName field is set to the value of the last call.
func (b *RestrictedRoleDefinitionSpecApplyConfiguration) WithTargetName(value string) *RestrictedRoleDefinitionSpecApplyConfiguration {
	b.TargetName = &value
	return b
}

// WithTargetNamespace sets the TargetNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetNamespace field is set to the value of the last call.
func (b *RestrictedRoleDefinitionSpecApplyConfiguration) WithTargetNamespace(value string) *RestrictedRoleDefinitionSpecApplyConfiguration {
	b.TargetNamespace = &value
	return b
}

// WithScopeNamespaced sets the ScopeNamespaced field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScopeNamespaced field is set to the value of the last call.
func (b *RestrictedRoleDefinitionSpecApplyConfiguration) WithScopeNamespaced(value bool) *RestrictedRoleDefinitionSpecApplyConfiguration {
	b.ScopeNamespaced = &value
	return b
}

// WithRestrictedAPIs adds the given value to the RestrictedAPIs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RestrictedAPIs field.
func (b *RestrictedRoleDefinitionSpecApplyConfiguration) WithRestrictedAPIs(values ...v1.APIGroup) *RestrictedRoleDefinitionSpecApplyConfiguration {
	for i := range values {
		b.RestrictedAPIs = append(b.RestrictedAPIs, values[i])
	}
	return b
}

// WithRestrictedResources adds the given value to the RestrictedResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RestrictedResources field.
func (b *RestrictedRoleDefinitionSpecApplyConfiguration) WithRestrictedResources(values ...v1.APIResource) *RestrictedRoleDefinitionSpecApplyConfiguration {
	for i := range values {
		b.RestrictedResources = append(b.RestrictedResources, values[i])
	}
	return b
}

// WithRestrictedVerbs adds the given value to the RestrictedVerbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RestrictedVerbs field.
func (b *RestrictedRoleDefinitionSpecApplyConfiguration) WithRestrictedVerbs(values ...string) *RestrictedRoleDefinitionSpecApplyConfiguration {
	for i := range values {
		b.RestrictedVerbs = append(b.RestrictedVerbs, values[i])
	}
	return b
}
