/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RestrictedAPIGroupApplyConfiguration represents a declarative configuration of the RestrictedAPIGroup type for use
// with apply.
//
// RestrictedAPIGroup defines an API group restriction with optional verb-level filtering.
// When Verbs is empty, the entire API group is blocked (all verbs restricted).
// When Verbs is specified, only the listed verbs are restricted across all resources in the group,
// and the remaining verbs are still allowed.
type RestrictedAPIGroupApplyConfiguration struct {
	// Name is the name of the API group (e.g., "storage.k8s.io", "velero.io").
	Name *string `json:"name,omitempty"`
	// Versions restricts only the specified API versions within this group.
	// When empty, all versions of the group are affected.
	Versions []v1.GroupVersionForDiscovery `json:"versions,omitempty"`
	// Verbs restricts only the specified verbs across all resources in this API group.
	// When empty, the entire API group is fully blocked (existing behavior).
	// When specified, only the listed verbs are removed from the generated role for resources
	// in this group — remaining verbs are still allowed.
	// This enables per-API-group read-only restrictions without enumerating every resource.
	// Note: "*" matches only the literal wildcard verb, not all verbs.
	Verbs []string `json:"verbs,omitempty"`
}

// RestrictedAPIGroupApplyConfiguration constructs a declarative configuration of the RestrictedAPIGroup type for use with
// apply.
func RestrictedAPIGroup() *RestrictedAPIGroupApplyConfiguration {
	return &RestrictedAPIGroupApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RestrictedAPIGroupApplyConfiguration) WithName(value string) *RestrictedAPIGroupApplyConfiguration {
	b.Name = &value
	return b
}

// WithVersions adds the given value to the Versions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Versions field.
func (b *RestrictedAPIGroupApplyConfiguration) WithVersions(values ...v1.GroupVersionForDiscovery) *RestrictedAPIGroupApplyConfiguration {
	for i := range values {
		b.Versions = append(b.Versions, values[i])
	}
	return b
}

// WithVerbs adds the given value to the Verbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Verbs field.
func (b *RestrictedAPIGroupApplyConfiguration) WithVerbs(values ...string) *RestrictedAPIGroupApplyConfiguration {
	for i := range values {
		b.Verbs = append(b.Verbs, values[i])
	}
	return b
}
