/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RoleLimitsApplyConfiguration represents a declarative configuration of the RoleLimits type for use
// with apply.
//
// RoleLimits defines constraints on roles created by RestrictedRoleDefinitions.
type RoleLimitsApplyConfiguration struct {
	// AllowClusterRoles controls whether ClusterRoles may be generated.
	// Default is false (deny by default).
	AllowClusterRoles *bool `json:"allowClusterRoles,omitempty"`
	// ForbiddenVerbs is a list of verbs that must not appear in generated roles.
	ForbiddenVerbs []string `json:"forbiddenVerbs,omitempty"`
	// ForbiddenResources is a list of resources that must not appear in generated roles.
	ForbiddenResources []string `json:"forbiddenResources,omitempty"`
	// ForbiddenAPIGroups is a list of API groups that must not appear in generated roles.
	ForbiddenAPIGroups []string `json:"forbiddenAPIGroups,omitempty"`
	// ForbiddenResourceVerbs is a list of specific resource+verb combinations that are forbidden.
	ForbiddenResourceVerbs []ResourceVerbRuleApplyConfiguration `json:"forbiddenResourceVerbs,omitempty"`
	// MaxRulesPerRole limits the number of rules in a single generated role.
	MaxRulesPerRole *int32 `json:"maxRulesPerRole,omitempty"`
}

// RoleLimitsApplyConfiguration constructs a declarative configuration of the RoleLimits type for use with
// apply.
func RoleLimits() *RoleLimitsApplyConfiguration {
	return &RoleLimitsApplyConfiguration{}
}

// WithAllowClusterRoles sets the AllowClusterRoles field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowClusterRoles field is set to the value of the last call.
func (b *RoleLimitsApplyConfiguration) WithAllowClusterRoles(value bool) *RoleLimitsApplyConfiguration {
	b.AllowClusterRoles = &value
	return b
}

// WithForbiddenVerbs adds the given value to the ForbiddenVerbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenVerbs field.
func (b *RoleLimitsApplyConfiguration) WithForbiddenVerbs(values ...string) *RoleLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenVerbs = append(b.ForbiddenVerbs, values[i])
	}
	return b
}

// WithForbiddenResources adds the given value to the ForbiddenResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenResources field.
func (b *RoleLimitsApplyConfiguration) WithForbiddenResources(values ...string) *RoleLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenResources = append(b.ForbiddenResources, values[i])
	}
	return b
}

// WithForbiddenAPIGroups adds the given value to the ForbiddenAPIGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenAPIGroups field.
func (b *RoleLimitsApplyConfiguration) WithForbiddenAPIGroups(values ...string) *RoleLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenAPIGroups = append(b.ForbiddenAPIGroups, values[i])
	}
	return b
}

// WithForbiddenResourceVerbs adds the given value to the ForbiddenResourceVerbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenResourceVerbs field.
func (b *RoleLimitsApplyConfiguration) WithForbiddenResourceVerbs(values ...*ResourceVerbRuleApplyConfiguration) *RoleLimitsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithForbiddenResourceVerbs")
		}
		b.ForbiddenResourceVerbs = append(b.ForbiddenResourceVerbs, *values[i])
	}
	return b
}

// WithMaxRulesPerRole sets the MaxRulesPerRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxRulesPerRole field is set to the value of the last call.
func (b *RoleLimitsApplyConfiguration) WithMaxRulesPerRole(value int32) *RoleLimitsApplyConfiguration {
	b.MaxRulesPerRole = &value
	return b
}
