/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	rbacv1 "k8s.io/api/rbac/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RoleDefinitionSpecApplyConfiguration represents a declarative configuration of the RoleDefinitionSpec type for use
// with apply.
//
// RoleDefinitionSpec defines the desired state of RoleDefinition.
type RoleDefinitionSpecApplyConfiguration struct {
	// TargetRole is the role type that will be reconciled. This can be a ClusterRole or a namespaced Role.
	// This field is immutable after creation; changing it would orphan the generated role and its bindings.
	TargetRole *string `json:"targetRole,omitempty"`
	// TargetName is the name of the target role. This can be any name that accurately describes the ClusterRole/Role.
	// Must be a valid Kubernetes name (max 63 characters for most resources).
	// This field is immutable after creation; changing it would orphan the generated role and its bindings.
	TargetName *string `json:"targetName,omitempty"`
	// TargetNamespace is the target namespace for the Role. Required when "TargetRole" is "Role".
	TargetNamespace *string `json:"targetNamespace,omitempty"`
	// ScopeNamespaced controls whether the API resource is namespaced or not. This can also be checked by
	// running `kubectl api-resources --namespaced=true/false`.
	ScopeNamespaced *bool `json:"scopeNamespaced,omitempty"`
	// RestrictedAPIs defines API group-level restrictions for the generated role.
	// Each entry can either fully block an API group or restrict only certain verbs:
	// - When Verbs is empty or omitted, the entire API group is fully blocked
	// (no resources from that group appear in the generated role).
	// - When Verbs is specified, only those verbs are removed for resources in
	// the group — the remaining verbs are still allowed (partial restriction).
	// Version filtering narrows which API versions are affected:
	// - When Versions is empty, all versions of the group are affected.
	// - When Versions is specified, only those API versions are restricted.
	// Note: Kubernetes RBAC PolicyRules are version-agnostic. If the same resource
	// exists in a non-restricted version of the same group, it will still appear
	// in the generated role.
	RestrictedAPIs []RestrictedAPIGroupApplyConfiguration `json:"restrictedApis,omitempty"`
	// RestrictedResources holds all resources which will *NOT* be reconciled into the "TargetRole".
	// The RBAC operator discovers all API resources available and removes those listed here.
	RestrictedResources []v1.APIResource `json:"restrictedResources,omitempty"`
	// RestrictedVerbs holds all verbs which will *NOT* be reconciled into the "TargetRole".
	// The RBAC operator discovers all resource verbs available and removes those listed here.
	RestrictedVerbs []string `json:"restrictedVerbs,omitempty"`
	// BreakglassAllowed marks generated ClusterRoles as eligible for temporary
	// privilege escalation via k8s-breakglass. The generated ClusterRole always
	// receives the label t-caas.telekom.com/breakglass-compatible set to "true"
	// or "false" based on this field's value.
	// Only applicable when TargetRole is ClusterRole. Defaults to false.
	BreakglassAllowed *bool `json:"breakglassAllowed,omitempty"`
	// AggregationLabels are additional labels applied to the generated ClusterRole so that
	// it participates in Kubernetes' built-in ClusterRole aggregation mechanism.
	// For example, setting `rbac.authorization.k8s.io/aggregate-to-view: "true"` causes the
	// generated ClusterRole's rules to be aggregated into the default "view" ClusterRole.
	// Only applicable when targetRole is ClusterRole.
	AggregationLabels map[string]string `json:"aggregationLabels,omitempty"`
	// AggregateFrom generates an aggregating ClusterRole that uses label selectors
	// to compose rules from other ClusterRoles, instead of specifying rules directly.
	// When set, the controller skips API discovery and filtering; the generated ClusterRole
	// carries an aggregationRule and its rules[] are managed by the RBAC aggregation controller.
	// Mutually exclusive with RestrictedAPIs, RestrictedResources, and RestrictedVerbs.
	// Only applicable when targetRole is ClusterRole.
	AggregateFrom *rbacv1.AggregationRule `json:"aggregateFrom,omitempty"`
}

// RoleDefinitionSpecApplyConfiguration constructs a declarative configuration of the RoleDefinitionSpec type for use with
// apply.
func RoleDefinitionSpec() *RoleDefinitionSpecApplyConfiguration {
	return &RoleDefinitionSpecApplyConfiguration{}
}

// WithTargetRole sets the TargetRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetRole field is set to the value of the last call.
func (b *RoleDefinitionSpecApplyConfiguration) WithTargetRole(value string) *RoleDefinitionSpecApplyConfiguration {
	b.TargetRole = &value
	return b
}

// WithTargetName sets the TargetName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetName field is set to the value of the last call.
func (b *RoleDefinitionSpecApplyConfiguration) WithTargetName(value string) *RoleDefinitionSpecApplyConfiguration {
	b.TargetName = &value
	return b
}

// WithTargetNamespace sets the TargetNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetNamespace field is set to the value of the last call.
func (b *RoleDefinitionSpecApplyConfiguration) WithTargetNamespace(value string) *RoleDefinitionSpecApplyConfiguration {
	b.TargetNamespace = &value
	return b
}

// WithScopeNamespaced sets the ScopeNamespaced field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScopeNamespaced field is set to the value of the last call.
func (b *RoleDefinitionSpecApplyConfiguration) WithScopeNamespaced(value bool) *RoleDefinitionSpecApplyConfiguration {
	b.ScopeNamespaced = &value
	return b
}

// WithRestrictedAPIs adds the given value to the RestrictedAPIs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RestrictedAPIs field.
func (b *RoleDefinitionSpecApplyConfiguration) WithRestrictedAPIs(values ...*RestrictedAPIGroupApplyConfiguration) *RoleDefinitionSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRestrictedAPIs")
		}
		b.RestrictedAPIs = append(b.RestrictedAPIs, *values[i])
	}
	return b
}

// WithRestrictedResources adds the given value to the RestrictedResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RestrictedResources field.
func (b *RoleDefinitionSpecApplyConfiguration) WithRestrictedResources(values ...v1.APIResource) *RoleDefinitionSpecApplyConfiguration {
	for i := range values {
		b.RestrictedResources = append(b.RestrictedResources, values[i])
	}
	return b
}

// WithRestrictedVerbs adds the given value to the RestrictedVerbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RestrictedVerbs field.
func (b *RoleDefinitionSpecApplyConfiguration) WithRestrictedVerbs(values ...string) *RoleDefinitionSpecApplyConfiguration {
	for i := range values {
		b.RestrictedVerbs = append(b.RestrictedVerbs, values[i])
	}
	return b
}

// WithBreakglassAllowed sets the BreakglassAllowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BreakglassAllowed field is set to the value of the last call.
func (b *RoleDefinitionSpecApplyConfiguration) WithBreakglassAllowed(value bool) *RoleDefinitionSpecApplyConfiguration {
	b.BreakglassAllowed = &value
	return b
}

// WithAggregationLabels puts the entries into the AggregationLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AggregationLabels field,
// overwriting an existing map entries in AggregationLabels field with the same key.
func (b *RoleDefinitionSpecApplyConfiguration) WithAggregationLabels(entries map[string]string) *RoleDefinitionSpecApplyConfiguration {
	if b.AggregationLabels == nil && len(entries) > 0 {
		b.AggregationLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.AggregationLabels[k] = v
	}
	return b
}

// WithAggregateFrom sets the AggregateFrom field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AggregateFrom field is set to the value of the last call.
func (b *RoleDefinitionSpecApplyConfiguration) WithAggregateFrom(value rbacv1.AggregationRule) *RoleDefinitionSpecApplyConfiguration {
	b.AggregateFrom = &value
	return b
}
