/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RoleDefinitionStatusApplyConfiguration represents a declarative configuration of the RoleDefinitionStatus type for use
// with apply.
//
// RoleDefinitionStatus defines the observed state of RoleDefinition.
type RoleDefinitionStatusApplyConfiguration struct {
	// ObservedGeneration is the last observed generation of the resource.
	// This is used by kstatus to determine if the resource is current.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Not extremely important as most status updates are driven by Conditions. We read the JSONPath from this status field to signify completed reconciliation.
	RoleReconciled *bool `json:"roleReconciled,omitempty"`
	// Conditions defines current service state of the Role definition. All conditions should evaluate to true to signify successful reconciliation.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// RoleDefinitionStatusApplyConfiguration constructs a declarative configuration of the RoleDefinitionStatus type for use with
// apply.
func RoleDefinitionStatus() *RoleDefinitionStatusApplyConfiguration {
	return &RoleDefinitionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *RoleDefinitionStatusApplyConfiguration) WithObservedGeneration(value int64) *RoleDefinitionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithRoleReconciled sets the RoleReconciled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleReconciled field is set to the value of the last call.
func (b *RoleDefinitionStatusApplyConfiguration) WithRoleReconciled(value bool) *RoleDefinitionStatusApplyConfiguration {
	b.RoleReconciled = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RoleDefinitionStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *RoleDefinitionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
