/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RoleRefLimitsApplyConfiguration represents a declarative configuration of the RoleRefLimits type for use
// with apply.
//
// RoleRefLimits controls which role references are allowed or forbidden.
type RoleRefLimitsApplyConfiguration struct {
	// AllowedRoleRefs is a list of allowed role names. Supports simple wildcards:
	// "prefix*" and "*suffix". An empty list means no role refs are allowed (default-deny).
	AllowedRoleRefs []string `json:"allowedRoleRefs,omitempty"`
	// AllowedRoleRefSelector selects allowed roles by label.
	AllowedRoleRefSelector *v1.LabelSelectorApplyConfiguration `json:"allowedRoleRefSelector,omitempty"`
	// ForbiddenRoleRefs is a list of explicitly forbidden role names.
	// Takes precedence over AllowedRoleRefs.
	ForbiddenRoleRefs []string `json:"forbiddenRoleRefs,omitempty"`
	// ForbiddenRoleRefSelector selects forbidden roles by label.
	ForbiddenRoleRefSelector *v1.LabelSelectorApplyConfiguration `json:"forbiddenRoleRefSelector,omitempty"`
}

// RoleRefLimitsApplyConfiguration constructs a declarative configuration of the RoleRefLimits type for use with
// apply.
func RoleRefLimits() *RoleRefLimitsApplyConfiguration {
	return &RoleRefLimitsApplyConfiguration{}
}

// WithAllowedRoleRefs adds the given value to the AllowedRoleRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedRoleRefs field.
func (b *RoleRefLimitsApplyConfiguration) WithAllowedRoleRefs(values ...string) *RoleRefLimitsApplyConfiguration {
	for i := range values {
		b.AllowedRoleRefs = append(b.AllowedRoleRefs, values[i])
	}
	return b
}

// WithAllowedRoleRefSelector sets the AllowedRoleRefSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowedRoleRefSelector field is set to the value of the last call.
func (b *RoleRefLimitsApplyConfiguration) WithAllowedRoleRefSelector(value *v1.LabelSelectorApplyConfiguration) *RoleRefLimitsApplyConfiguration {
	b.AllowedRoleRefSelector = value
	return b
}

// WithForbiddenRoleRefs adds the given value to the ForbiddenRoleRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenRoleRefs field.
func (b *RoleRefLimitsApplyConfiguration) WithForbiddenRoleRefs(values ...string) *RoleRefLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenRoleRefs = append(b.ForbiddenRoleRefs, values[i])
	}
	return b
}

// WithForbiddenRoleRefSelector sets the ForbiddenRoleRefSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ForbiddenRoleRefSelector field is set to the value of the last call.
func (b *RoleRefLimitsApplyConfiguration) WithForbiddenRoleRefSelector(value *v1.LabelSelectorApplyConfiguration) *RoleRefLimitsApplyConfiguration {
	b.ForbiddenRoleRefSelector = value
	return b
}
