/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SACreationConfigApplyConfiguration represents a declarative configuration of the SACreationConfig type for use
// with apply.
//
// SACreationConfig controls ServiceAccount auto-creation behaviour.
type SACreationConfigApplyConfiguration struct {
	// AllowAutoCreate controls whether ServiceAccounts may be auto-created.
	AllowAutoCreate *bool `json:"allowAutoCreate,omitempty"`
	// AllowedCreationNamespaceSelector selects namespaces where SA creation is allowed.
	AllowedCreationNamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"allowedCreationNamespaceSelector,omitempty"`
	// AllowedCreationNamespaces is an explicit list of namespaces where SA creation is allowed.
	AllowedCreationNamespaces []string `json:"allowedCreationNamespaces,omitempty"`
	// AutomountServiceAccountToken controls automount for auto-created SAs.
	AutomountServiceAccountToken *bool `json:"automountServiceAccountToken,omitempty"`
	// DisableAdoption prevents adoption of pre-existing ServiceAccounts.
	DisableAdoption *bool `json:"disableAdoption,omitempty"`
}

// SACreationConfigApplyConfiguration constructs a declarative configuration of the SACreationConfig type for use with
// apply.
func SACreationConfig() *SACreationConfigApplyConfiguration {
	return &SACreationConfigApplyConfiguration{}
}

// WithAllowAutoCreate sets the AllowAutoCreate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowAutoCreate field is set to the value of the last call.
func (b *SACreationConfigApplyConfiguration) WithAllowAutoCreate(value bool) *SACreationConfigApplyConfiguration {
	b.AllowAutoCreate = &value
	return b
}

// WithAllowedCreationNamespaceSelector sets the AllowedCreationNamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowedCreationNamespaceSelector field is set to the value of the last call.
func (b *SACreationConfigApplyConfiguration) WithAllowedCreationNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *SACreationConfigApplyConfiguration {
	b.AllowedCreationNamespaceSelector = value
	return b
}

// WithAllowedCreationNamespaces adds the given value to the AllowedCreationNamespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedCreationNamespaces field.
func (b *SACreationConfigApplyConfiguration) WithAllowedCreationNamespaces(values ...string) *SACreationConfigApplyConfiguration {
	for i := range values {
		b.AllowedCreationNamespaces = append(b.AllowedCreationNamespaces, values[i])
	}
	return b
}

// WithAutomountServiceAccountToken sets the AutomountServiceAccountToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutomountServiceAccountToken field is set to the value of the last call.
func (b *SACreationConfigApplyConfiguration) WithAutomountServiceAccountToken(value bool) *SACreationConfigApplyConfiguration {
	b.AutomountServiceAccountToken = &value
	return b
}

// WithDisableAdoption sets the DisableAdoption field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisableAdoption field is set to the value of the last call.
func (b *SACreationConfigApplyConfiguration) WithDisableAdoption(value bool) *SACreationConfigApplyConfiguration {
	b.DisableAdoption = &value
	return b
}
