/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ServiceAccountLimitsApplyConfiguration represents a declarative configuration of the ServiceAccountLimits type for use
// with apply.
//
// ServiceAccountLimits defines constraints on ServiceAccount subjects.
type ServiceAccountLimitsApplyConfiguration struct {
	// AllowedNamespaceSelector selects namespaces whose SAs may be referenced.
	AllowedNamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"allowedNamespaceSelector,omitempty"`
	// ForbiddenNamespaces is a list of namespaces whose SAs may not be referenced.
	ForbiddenNamespaces []string `json:"forbiddenNamespaces,omitempty"`
	// ForbiddenNamespacePrefixes is a list of namespace prefixes to deny.
	ForbiddenNamespacePrefixes []string `json:"forbiddenNamespacePrefixes,omitempty"`
	// Creation constrains ServiceAccount auto-creation behaviour.
	Creation *SACreationConfigApplyConfiguration `json:"creation,omitempty"`
}

// ServiceAccountLimitsApplyConfiguration constructs a declarative configuration of the ServiceAccountLimits type for use with
// apply.
func ServiceAccountLimits() *ServiceAccountLimitsApplyConfiguration {
	return &ServiceAccountLimitsApplyConfiguration{}
}

// WithAllowedNamespaceSelector sets the AllowedNamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowedNamespaceSelector field is set to the value of the last call.
func (b *ServiceAccountLimitsApplyConfiguration) WithAllowedNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *ServiceAccountLimitsApplyConfiguration {
	b.AllowedNamespaceSelector = value
	return b
}

// WithForbiddenNamespaces adds the given value to the ForbiddenNamespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenNamespaces field.
func (b *ServiceAccountLimitsApplyConfiguration) WithForbiddenNamespaces(values ...string) *ServiceAccountLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenNamespaces = append(b.ForbiddenNamespaces, values[i])
	}
	return b
}

// WithForbiddenNamespacePrefixes adds the given value to the ForbiddenNamespacePrefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenNamespacePrefixes field.
func (b *ServiceAccountLimitsApplyConfiguration) WithForbiddenNamespacePrefixes(values ...string) *ServiceAccountLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenNamespacePrefixes = append(b.ForbiddenNamespacePrefixes, values[i])
	}
	return b
}

// WithCreation sets the Creation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Creation field is set to the value of the last call.
func (b *ServiceAccountLimitsApplyConfiguration) WithCreation(value *SACreationConfigApplyConfiguration) *ServiceAccountLimitsApplyConfiguration {
	b.Creation = value
	return b
}
