/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SubjectLimitsApplyConfiguration represents a declarative configuration of the SubjectLimits type for use
// with apply.
//
// SubjectLimits defines constraints on the subjects a tenant may use.
type SubjectLimitsApplyConfiguration struct {
	// AllowedKinds controls which subject kinds are allowed.
	// Valid values: "User", "Group", "ServiceAccount".
	// An empty list means no subject kinds are allowed (default-deny).
	AllowedKinds []string `json:"allowedKinds,omitempty"`
	// ForbiddenKinds lists subject kinds that are explicitly forbidden.
	// Takes precedence over AllowedKinds.
	ForbiddenKinds []string `json:"forbiddenKinds,omitempty"`
	// UserLimits constrains User subject names.
	UserLimits *NameMatchLimitsApplyConfiguration `json:"userLimits,omitempty"`
	// GroupLimits constrains Group subject names.
	GroupLimits *NameMatchLimitsApplyConfiguration `json:"groupLimits,omitempty"`
	// ServiceAccountLimits constrains ServiceAccount subjects.
	ServiceAccountLimits *ServiceAccountLimitsApplyConfiguration `json:"serviceAccountLimits,omitempty"`
}

// SubjectLimitsApplyConfiguration constructs a declarative configuration of the SubjectLimits type for use with
// apply.
func SubjectLimits() *SubjectLimitsApplyConfiguration {
	return &SubjectLimitsApplyConfiguration{}
}

// WithAllowedKinds adds the given value to the AllowedKinds field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedKinds field.
func (b *SubjectLimitsApplyConfiguration) WithAllowedKinds(values ...string) *SubjectLimitsApplyConfiguration {
	for i := range values {
		b.AllowedKinds = append(b.AllowedKinds, values[i])
	}
	return b
}

// WithForbiddenKinds adds the given value to the ForbiddenKinds field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenKinds field.
func (b *SubjectLimitsApplyConfiguration) WithForbiddenKinds(values ...string) *SubjectLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenKinds = append(b.ForbiddenKinds, values[i])
	}
	return b
}

// WithUserLimits sets the UserLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserLimits field is set to the value of the last call.
func (b *SubjectLimitsApplyConfiguration) WithUserLimits(value *NameMatchLimitsApplyConfiguration) *SubjectLimitsApplyConfiguration {
	b.UserLimits = value
	return b
}

// WithGroupLimits sets the GroupLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupLimits field is set to the value of the last call.
func (b *SubjectLimitsApplyConfiguration) WithGroupLimits(value *NameMatchLimitsApplyConfiguration) *SubjectLimitsApplyConfiguration {
	b.GroupLimits = value
	return b
}

// WithServiceAccountLimits sets the ServiceAccountLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountLimits field is set to the value of the last call.
func (b *SubjectLimitsApplyConfiguration) WithServiceAccountLimits(value *ServiceAccountLimitsApplyConfiguration) *SubjectLimitsApplyConfiguration {
	b.ServiceAccountLimits = value
	return b
}
