/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/authorization/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// WebhookAuthorizerSpecApplyConfiguration represents a declarative configuration of the WebhookAuthorizerSpec type for use
// with apply.
//
// WebhookAuthorizerSpec defines the desired state of WebhookAuthorizer.
type WebhookAuthorizerSpecApplyConfiguration struct {
	// Resources which will be used to evaluate the SubjectAccessReviewSpec.ResourceAttributes
	ResourceRules []v1.ResourceRule `json:"resourceRules,omitempty"`
	// Resources which will be used to evaluate the SubjectAccessReviewSpec.NonResourceAttributes
	NonResourceRules []v1.NonResourceRule `json:"nonResourceRules,omitempty"`
	// AllowedPrincipals is a slice of principals this authorizer should allow.
	AllowedPrincipals []PrincipalApplyConfiguration `json:"allowedPrincipals,omitempty"`
	// DeniedPrincipals is a slice of principals this authorizer should deny.
	DeniedPrincipals []PrincipalApplyConfiguration `json:"deniedPrincipals,omitempty"`
	// NamespaceSelector is a label selector to match namespaces that should allow the specified API calls.
	NamespaceSelector *metav1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
}

// WebhookAuthorizerSpecApplyConfiguration constructs a declarative configuration of the WebhookAuthorizerSpec type for use with
// apply.
func WebhookAuthorizerSpec() *WebhookAuthorizerSpecApplyConfiguration {
	return &WebhookAuthorizerSpecApplyConfiguration{}
}

// WithResourceRules adds the given value to the ResourceRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceRules field.
func (b *WebhookAuthorizerSpecApplyConfiguration) WithResourceRules(values ...v1.ResourceRule) *WebhookAuthorizerSpecApplyConfiguration {
	for i := range values {
		b.ResourceRules = append(b.ResourceRules, values[i])
	}
	return b
}

// WithNonResourceRules adds the given value to the NonResourceRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NonResourceRules field.
func (b *WebhookAuthorizerSpecApplyConfiguration) WithNonResourceRules(values ...v1.NonResourceRule) *WebhookAuthorizerSpecApplyConfiguration {
	for i := range values {
		b.NonResourceRules = append(b.NonResourceRules, values[i])
	}
	return b
}

// WithAllowedPrincipals adds the given value to the AllowedPrincipals field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedPrincipals field.
func (b *WebhookAuthorizerSpecApplyConfiguration) WithAllowedPrincipals(values ...*PrincipalApplyConfiguration) *WebhookAuthorizerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAllowedPrincipals")
		}
		b.AllowedPrincipals = append(b.AllowedPrincipals, *values[i])
	}
	return b
}

// WithDeniedPrincipals adds the given value to the DeniedPrincipals field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DeniedPrincipals field.
func (b *WebhookAuthorizerSpecApplyConfiguration) WithDeniedPrincipals(values ...*PrincipalApplyConfiguration) *WebhookAuthorizerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDeniedPrincipals")
		}
		b.DeniedPrincipals = append(b.DeniedPrincipals, *values[i])
	}
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *WebhookAuthorizerSpecApplyConfiguration) WithNamespaceSelector(value *metav1.LabelSelectorApplyConfiguration) *WebhookAuthorizerSpecApplyConfiguration {
	b.NamespaceSelector = value
	return b
}
