/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// WebhookAuthorizerStatusApplyConfiguration represents a declarative configuration of the WebhookAuthorizerStatus type for use
// with apply.
//
// WebhookAuthorizerStatus defines the observed state of WebhookAuthorizer
type WebhookAuthorizerStatusApplyConfiguration struct {
	// ObservedGeneration is the last observed generation of the resource.
	// This is used by kstatus to determine if the resource is current.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Not extremely important as most status updates are driven by Conditions. We read the JSONPath from this status field to signify webhook authorizer as configured.
	AuthorizerConfigured *bool `json:"authorizerConfigured,omitempty"`
	// Conditions defines current service state of the Webhook authorizer. All conditions should evaluate to true to signify successful configuration.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// WebhookAuthorizerStatusApplyConfiguration constructs a declarative configuration of the WebhookAuthorizerStatus type for use with
// apply.
func WebhookAuthorizerStatus() *WebhookAuthorizerStatusApplyConfiguration {
	return &WebhookAuthorizerStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *WebhookAuthorizerStatusApplyConfiguration) WithObservedGeneration(value int64) *WebhookAuthorizerStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithAuthorizerConfigured sets the AuthorizerConfigured field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorizerConfigured field is set to the value of the last call.
func (b *WebhookAuthorizerStatusApplyConfiguration) WithAuthorizerConfigured(value bool) *WebhookAuthorizerStatusApplyConfiguration {
	b.AuthorizerConfigured = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *WebhookAuthorizerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *WebhookAuthorizerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
