# SPDX-FileCopyrightText: 2026 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: 'Setup Go Environment'
description: 'Setup Go with caching and optional tools installation'

inputs:
  go-version-file:
    description: 'Path to go.mod file for Go version (single source of truth)'
    required: false
    default: 'go.mod'
  install-kind:
    description: 'Install kind CLI'
    required: false
    default: 'false'
  kind-version:
    description: 'Kind version to install'
    required: false
    default: 'v0.31.0'
  install-helm:
    description: 'Install Helm CLI'
    required: false
    default: 'false'
  helm-version:
    description: 'Helm version to install'
    required: false
    default: 'v3.17.0'
  install-golangci-lint:
    description: 'Install golangci-lint'
    required: false
    default: 'false'
  golangci-lint-version:
    description: 'golangci-lint version to install'
    required: false
    default: 'v2.8.0'
  cache-dependency-path:
    description: 'Path to go.sum for cache key'
    required: false
    default: 'go.sum'

runs:
  using: 'composite'
  steps:
    - name: Extract Go version from toolchain or go directive
      id: go-version
      shell: bash
      run: |
        GO_MOD="${{ inputs.go-version-file }}"
        # Prefer toolchain directive, fall back to go directive
        VERSION=$(grep -E '^toolchain go' "$GO_MOD" | sed 's/toolchain go//' || true)
        if [ -z "$VERSION" ]; then
          VERSION=$(grep -E '^go [0-9]' "$GO_MOD" | awk '{print $2}')
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Using Go version: $VERSION"

    - name: Setup Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: ${{ steps.go-version.outputs.version }}
        cache: true
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Install kind
      if: inputs.install-kind == 'true'
      shell: bash
      run: go install sigs.k8s.io/kind@${{ inputs.kind-version }}

    - name: Install Helm
      if: inputs.install-helm == 'true'
      uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      with:
        version: ${{ inputs.helm-version }}

    - name: Install golangci-lint
      if: inputs.install-golangci-lint == 'true'
      shell: bash
      run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@${{ inputs.golangci-lint-version }}
