// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/client/client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/client/client.go -destination=pkg/test/mock/client.go -package=idpclient
//

// Package idpclient is a generated GoMock package.
package idpclient

import (
	reflect "reflect"

	logr "github.com/go-logr/logr"
	"gitlab.devops.telekom.de/cit/t-caas/operators/auth-operator/pkg/idpclient"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockClient) CreateGroup(group idpclient.Group) ([]idpclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", group)
	ret0, _ := ret[0].([]idpclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockClientMockRecorder) CreateGroup(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockClient)(nil).CreateGroup), group)
}

// CreateGroupMembers mocks base method.
func (m *MockClient) CreateGroupMembers(group idpclient.Group, members []idpclient.User) ([]idpclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroupMembers", group, members)
	ret0, _ := ret[0].([]idpclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroupMembers indicates an expected call of CreateGroupMembers.
func (mr *MockClientMockRecorder) CreateGroupMembers(group, members any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupMembers", reflect.TypeOf((*MockClient)(nil).CreateGroupMembers), group, members)
}

// CreateGroupOwners mocks base method.
func (m *MockClient) CreateGroupOwners(group idpclient.Group, owners []idpclient.User) ([]idpclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroupOwners", group, owners)
	ret0, _ := ret[0].([]idpclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroupOwners indicates an expected call of CreateGroupOwners.
func (mr *MockClientMockRecorder) CreateGroupOwners(group, owners any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupOwners", reflect.TypeOf((*MockClient)(nil).CreateGroupOwners), group, owners)
}

// DeleteGroup mocks base method.
func (m *MockClient) DeleteGroup(group idpclient.Group) ([]idpclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", group)
	ret0, _ := ret[0].([]idpclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockClientMockRecorder) DeleteGroup(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockClient)(nil).DeleteGroup), group)
}

// DeleteGroupMembers mocks base method.
func (m *MockClient) DeleteGroupMembers(group idpclient.Group, members []idpclient.User) ([]idpclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroupMembers", group, members)
	ret0, _ := ret[0].([]idpclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGroupMembers indicates an expected call of DeleteGroupMembers.
func (mr *MockClientMockRecorder) DeleteGroupMembers(group, members any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroupMembers", reflect.TypeOf((*MockClient)(nil).DeleteGroupMembers), group, members)
}

// DeleteGroupOwners mocks base method.
func (m *MockClient) DeleteGroupOwners(group idpclient.Group, owners []idpclient.User) ([]idpclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroupOwners", group, owners)
	ret0, _ := ret[0].([]idpclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGroupOwners indicates an expected call of DeleteGroupOwners.
func (mr *MockClientMockRecorder) DeleteGroupOwners(group, owners any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroupOwners", reflect.TypeOf((*MockClient)(nil).DeleteGroupOwners), group, owners)
}

// GetGroup mocks base method.
func (m *MockClient) GetGroup(group idpclient.Group) ([]idpclient.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", group)
	ret0, _ := ret[0].([]idpclient.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockClientMockRecorder) GetGroup(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockClient)(nil).GetGroup), group)
}

// GetGroupMembers mocks base method.
func (m *MockClient) GetGroupMembers(group idpclient.Group) ([]idpclient.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupMembers", group)
	ret0, _ := ret[0].([]idpclient.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupMembers indicates an expected call of GetGroupMembers.
func (mr *MockClientMockRecorder) GetGroupMembers(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupMembers", reflect.TypeOf((*MockClient)(nil).GetGroupMembers), group)
}

// GetGroupOwners mocks base method.
func (m *MockClient) GetGroupOwners(group idpclient.Group) ([]idpclient.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupOwners", group)
	ret0, _ := ret[0].([]idpclient.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupOwners indicates an expected call of GetGroupOwners.
func (mr *MockClientMockRecorder) GetGroupOwners(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupOwners", reflect.TypeOf((*MockClient)(nil).GetGroupOwners), group)
}

// RefreshAccessToken mocks base method.
func (m *MockClient) RefreshAccessToken() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshAccessToken")
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshAccessToken indicates an expected call of RefreshAccessToken.
func (mr *MockClientMockRecorder) RefreshAccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshAccessToken", reflect.TypeOf((*MockClient)(nil).RefreshAccessToken))
}

// SetLogger mocks base method.
func (m *MockClient) SetLogger(logger logr.Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", logger)
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockClientMockRecorder) SetLogger(logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockClient)(nil).SetLogger), logger)
}
