/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/telekom/auth-operator/api/authorization/v1alpha1"
	authorizationv1alpha1 "github.com/telekom/auth-operator/api/authorization/v1alpha1/applyconfiguration/authorization/v1alpha1"
	internal "github.com/telekom/auth-operator/api/authorization/v1alpha1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=authorization.t-caas.telekom.com, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("BindDefinition"):
		return &authorizationv1alpha1.BindDefinitionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BindDefinitionSpec"):
		return &authorizationv1alpha1.BindDefinitionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BindDefinitionStatus"):
		return &authorizationv1alpha1.BindDefinitionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BindingLimits"):
		return &authorizationv1alpha1.BindingLimitsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterBinding"):
		return &authorizationv1alpha1.ClusterBindingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DefaultPolicyAssignment"):
		return &authorizationv1alpha1.DefaultPolicyAssignmentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ImpersonationConfig"):
		return &authorizationv1alpha1.ImpersonationConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NameMatchLimits"):
		return &authorizationv1alpha1.NameMatchLimitsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NamespaceBinding"):
		return &authorizationv1alpha1.NamespaceBindingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NamespaceLimits"):
		return &authorizationv1alpha1.NamespaceLimitsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PolicyScope"):
		return &authorizationv1alpha1.PolicyScopeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Principal"):
		return &authorizationv1alpha1.PrincipalApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RBACPolicy"):
		return &authorizationv1alpha1.RBACPolicyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RBACPolicyReference"):
		return &authorizationv1alpha1.RBACPolicyReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RBACPolicySpec"):
		return &authorizationv1alpha1.RBACPolicySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RBACPolicyStatus"):
		return &authorizationv1alpha1.RBACPolicyStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ResourceVerbRule"):
		return &authorizationv1alpha1.ResourceVerbRuleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RestrictedAPIGroup"):
		return &authorizationv1alpha1.RestrictedAPIGroupApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RestrictedBindDefinition"):
		return &authorizationv1alpha1.RestrictedBindDefinitionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RestrictedBindDefinitionSpec"):
		return &authorizationv1alpha1.RestrictedBindDefinitionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RestrictedBindDefinitionStatus"):
		return &authorizationv1alpha1.RestrictedBindDefinitionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RestrictedRoleDefinition"):
		return &authorizationv1alpha1.RestrictedRoleDefinitionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RestrictedRoleDefinitionSpec"):
		return &authorizationv1alpha1.RestrictedRoleDefinitionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RestrictedRoleDefinitionStatus"):
		return &authorizationv1alpha1.RestrictedRoleDefinitionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RoleDefinition"):
		return &authorizationv1alpha1.RoleDefinitionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RoleDefinitionSpec"):
		return &authorizationv1alpha1.RoleDefinitionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RoleDefinitionStatus"):
		return &authorizationv1alpha1.RoleDefinitionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RoleLimits"):
		return &authorizationv1alpha1.RoleLimitsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RoleRefLimits"):
		return &authorizationv1alpha1.RoleRefLimitsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SACreationConfig"):
		return &authorizationv1alpha1.SACreationConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SARef"):
		return &authorizationv1alpha1.SARefApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceAccountLimits"):
		return &authorizationv1alpha1.ServiceAccountLimitsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubjectLimits"):
		return &authorizationv1alpha1.SubjectLimitsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("WebhookAuthorizer"):
		return &authorizationv1alpha1.WebhookAuthorizerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("WebhookAuthorizerSpec"):
		return &authorizationv1alpha1.WebhookAuthorizerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("WebhookAuthorizerStatus"):
		return &authorizationv1alpha1.WebhookAuthorizerStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
