//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	authorizationv1 "k8s.io/api/authorization/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindDefinition) DeepCopyInto(out *BindDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindDefinition.
func (in *BindDefinition) DeepCopy() *BindDefinition {
	if in == nil {
		return nil
	}
	out := new(BindDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BindDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindDefinitionList) DeepCopyInto(out *BindDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BindDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindDefinitionList.
func (in *BindDefinitionList) DeepCopy() *BindDefinitionList {
	if in == nil {
		return nil
	}
	out := new(BindDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BindDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindDefinitionSpec) DeepCopyInto(out *BindDefinitionSpec) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]rbacv1.Subject, len(*in))
		copy(*out, *in)
	}
	in.ClusterRoleBindings.DeepCopyInto(&out.ClusterRoleBindings)
	if in.RoleBindings != nil {
		in, out := &in.RoleBindings, &out.RoleBindings
		*out = make([]NamespaceBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutomountServiceAccountToken != nil {
		in, out := &in.AutomountServiceAccountToken, &out.AutomountServiceAccountToken
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindDefinitionSpec.
func (in *BindDefinitionSpec) DeepCopy() *BindDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(BindDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindDefinitionStatus) DeepCopyInto(out *BindDefinitionStatus) {
	*out = *in
	if in.GeneratedServiceAccounts != nil {
		in, out := &in.GeneratedServiceAccounts, &out.GeneratedServiceAccounts
		*out = make([]rbacv1.Subject, len(*in))
		copy(*out, *in)
	}
	if in.MissingRoleRefs != nil {
		in, out := &in.MissingRoleRefs, &out.MissingRoleRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExternalServiceAccounts != nil {
		in, out := &in.ExternalServiceAccounts, &out.ExternalServiceAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindDefinitionStatus.
func (in *BindDefinitionStatus) DeepCopy() *BindDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(BindDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingLimits) DeepCopyInto(out *BindingLimits) {
	*out = *in
	if in.ClusterRoleBindingLimits != nil {
		in, out := &in.ClusterRoleBindingLimits, &out.ClusterRoleBindingLimits
		*out = new(RoleRefLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleBindingLimits != nil {
		in, out := &in.RoleBindingLimits, &out.RoleBindingLimits
		*out = new(RoleRefLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetNamespaceLimits != nil {
		in, out := &in.TargetNamespaceLimits, &out.TargetNamespaceLimits
		*out = new(NamespaceLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingLimits.
func (in *BindingLimits) DeepCopy() *BindingLimits {
	if in == nil {
		return nil
	}
	out := new(BindingLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBinding) DeepCopyInto(out *ClusterBinding) {
	*out = *in
	if in.ClusterRoleRefs != nil {
		in, out := &in.ClusterRoleRefs, &out.ClusterRoleRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBinding.
func (in *ClusterBinding) DeepCopy() *ClusterBinding {
	if in == nil {
		return nil
	}
	out := new(ClusterBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPolicyAssignment) DeepCopyInto(out *DefaultPolicyAssignment) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = make([]SARef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPolicyAssignment.
func (in *DefaultPolicyAssignment) DeepCopy() *DefaultPolicyAssignment {
	if in == nil {
		return nil
	}
	out := new(DefaultPolicyAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImpersonationConfig) DeepCopyInto(out *ImpersonationConfig) {
	*out = *in
	if in.ServiceAccountRef != nil {
		in, out := &in.ServiceAccountRef, &out.ServiceAccountRef
		*out = new(SARef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImpersonationConfig.
func (in *ImpersonationConfig) DeepCopy() *ImpersonationConfig {
	if in == nil {
		return nil
	}
	out := new(ImpersonationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameMatchLimits) DeepCopyInto(out *NameMatchLimits) {
	*out = *in
	if in.AllowedNames != nil {
		in, out := &in.AllowedNames, &out.AllowedNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenNames != nil {
		in, out := &in.ForbiddenNames, &out.ForbiddenNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedPrefixes != nil {
		in, out := &in.AllowedPrefixes, &out.AllowedPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenPrefixes != nil {
		in, out := &in.ForbiddenPrefixes, &out.ForbiddenPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedSuffixes != nil {
		in, out := &in.AllowedSuffixes, &out.AllowedSuffixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenSuffixes != nil {
		in, out := &in.ForbiddenSuffixes, &out.ForbiddenSuffixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameMatchLimits.
func (in *NameMatchLimits) DeepCopy() *NameMatchLimits {
	if in == nil {
		return nil
	}
	out := new(NameMatchLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBinding) DeepCopyInto(out *NamespaceBinding) {
	*out = *in
	if in.ClusterRoleRefs != nil {
		in, out := &in.ClusterRoleRefs, &out.ClusterRoleRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RoleRefs != nil {
		in, out := &in.RoleRefs, &out.RoleRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = make([]v1.LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBinding.
func (in *NamespaceBinding) DeepCopy() *NamespaceBinding {
	if in == nil {
		return nil
	}
	out := new(NamespaceBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceLimits) DeepCopyInto(out *NamespaceLimits) {
	*out = *in
	if in.AllowedNamespaceSelector != nil {
		in, out := &in.AllowedNamespaceSelector, &out.AllowedNamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ForbiddenNamespaces != nil {
		in, out := &in.ForbiddenNamespaces, &out.ForbiddenNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenNamespacePrefixes != nil {
		in, out := &in.ForbiddenNamespacePrefixes, &out.ForbiddenNamespacePrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxTargetNamespaces != nil {
		in, out := &in.MaxTargetNamespaces, &out.MaxTargetNamespaces
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceLimits.
func (in *NamespaceLimits) DeepCopy() *NamespaceLimits {
	if in == nil {
		return nil
	}
	out := new(NamespaceLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyScope) DeepCopyInto(out *PolicyScope) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyScope.
func (in *PolicyScope) DeepCopy() *PolicyScope {
	if in == nil {
		return nil
	}
	out := new(PolicyScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Principal) DeepCopyInto(out *Principal) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Principal.
func (in *Principal) DeepCopy() *Principal {
	if in == nil {
		return nil
	}
	out := new(Principal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACPolicy) DeepCopyInto(out *RBACPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACPolicy.
func (in *RBACPolicy) DeepCopy() *RBACPolicy {
	if in == nil {
		return nil
	}
	out := new(RBACPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RBACPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACPolicyList) DeepCopyInto(out *RBACPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RBACPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACPolicyList.
func (in *RBACPolicyList) DeepCopy() *RBACPolicyList {
	if in == nil {
		return nil
	}
	out := new(RBACPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RBACPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACPolicyReference) DeepCopyInto(out *RBACPolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACPolicyReference.
func (in *RBACPolicyReference) DeepCopy() *RBACPolicyReference {
	if in == nil {
		return nil
	}
	out := new(RBACPolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACPolicySpec) DeepCopyInto(out *RBACPolicySpec) {
	*out = *in
	in.AppliesTo.DeepCopyInto(&out.AppliesTo)
	if in.BindingLimits != nil {
		in, out := &in.BindingLimits, &out.BindingLimits
		*out = new(BindingLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleLimits != nil {
		in, out := &in.RoleLimits, &out.RoleLimits
		*out = new(RoleLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.SubjectLimits != nil {
		in, out := &in.SubjectLimits, &out.SubjectLimits
		*out = new(SubjectLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultAssignment != nil {
		in, out := &in.DefaultAssignment, &out.DefaultAssignment
		*out = new(DefaultPolicyAssignment)
		(*in).DeepCopyInto(*out)
	}
	if in.Impersonation != nil {
		in, out := &in.Impersonation, &out.Impersonation
		*out = new(ImpersonationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACPolicySpec.
func (in *RBACPolicySpec) DeepCopy() *RBACPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RBACPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACPolicyStatus) DeepCopyInto(out *RBACPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACPolicyStatus.
func (in *RBACPolicyStatus) DeepCopy() *RBACPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RBACPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceVerbRule) DeepCopyInto(out *ResourceVerbRule) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceVerbRule.
func (in *ResourceVerbRule) DeepCopy() *ResourceVerbRule {
	if in == nil {
		return nil
	}
	out := new(ResourceVerbRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedBindDefinition) DeepCopyInto(out *RestrictedBindDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedBindDefinition.
func (in *RestrictedBindDefinition) DeepCopy() *RestrictedBindDefinition {
	if in == nil {
		return nil
	}
	out := new(RestrictedBindDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestrictedBindDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedBindDefinitionList) DeepCopyInto(out *RestrictedBindDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RestrictedBindDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedBindDefinitionList.
func (in *RestrictedBindDefinitionList) DeepCopy() *RestrictedBindDefinitionList {
	if in == nil {
		return nil
	}
	out := new(RestrictedBindDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestrictedBindDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedBindDefinitionSpec) DeepCopyInto(out *RestrictedBindDefinitionSpec) {
	*out = *in
	out.PolicyRef = in.PolicyRef
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]rbacv1.Subject, len(*in))
		copy(*out, *in)
	}
	if in.ClusterRoleBindings != nil {
		in, out := &in.ClusterRoleBindings, &out.ClusterRoleBindings
		*out = new(ClusterBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleBindings != nil {
		in, out := &in.RoleBindings, &out.RoleBindings
		*out = make([]NamespaceBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutomountServiceAccountToken != nil {
		in, out := &in.AutomountServiceAccountToken, &out.AutomountServiceAccountToken
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedBindDefinitionSpec.
func (in *RestrictedBindDefinitionSpec) DeepCopy() *RestrictedBindDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(RestrictedBindDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedBindDefinitionStatus) DeepCopyInto(out *RestrictedBindDefinitionStatus) {
	*out = *in
	if in.GeneratedServiceAccounts != nil {
		in, out := &in.GeneratedServiceAccounts, &out.GeneratedServiceAccounts
		*out = make([]rbacv1.Subject, len(*in))
		copy(*out, *in)
	}
	if in.MissingRoleRefs != nil {
		in, out := &in.MissingRoleRefs, &out.MissingRoleRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExternalServiceAccounts != nil {
		in, out := &in.ExternalServiceAccounts, &out.ExternalServiceAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyViolations != nil {
		in, out := &in.PolicyViolations, &out.PolicyViolations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedBindDefinitionStatus.
func (in *RestrictedBindDefinitionStatus) DeepCopy() *RestrictedBindDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(RestrictedBindDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedRoleDefinition) DeepCopyInto(out *RestrictedRoleDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedRoleDefinition.
func (in *RestrictedRoleDefinition) DeepCopy() *RestrictedRoleDefinition {
	if in == nil {
		return nil
	}
	out := new(RestrictedRoleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestrictedRoleDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedRoleDefinitionList) DeepCopyInto(out *RestrictedRoleDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RestrictedRoleDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedRoleDefinitionList.
func (in *RestrictedRoleDefinitionList) DeepCopy() *RestrictedRoleDefinitionList {
	if in == nil {
		return nil
	}
	out := new(RestrictedRoleDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestrictedRoleDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedRoleDefinitionSpec) DeepCopyInto(out *RestrictedRoleDefinitionSpec) {
	*out = *in
	out.PolicyRef = in.PolicyRef
	if in.RestrictedAPIs != nil {
		in, out := &in.RestrictedAPIs, &out.RestrictedAPIs
		*out = make([]v1.APIGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RestrictedResources != nil {
		in, out := &in.RestrictedResources, &out.RestrictedResources
		*out = make([]v1.APIResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RestrictedVerbs != nil {
		in, out := &in.RestrictedVerbs, &out.RestrictedVerbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedRoleDefinitionSpec.
func (in *RestrictedRoleDefinitionSpec) DeepCopy() *RestrictedRoleDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(RestrictedRoleDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedRoleDefinitionStatus) DeepCopyInto(out *RestrictedRoleDefinitionStatus) {
	*out = *in
	if in.PolicyViolations != nil {
		in, out := &in.PolicyViolations, &out.PolicyViolations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedRoleDefinitionStatus.
func (in *RestrictedRoleDefinitionStatus) DeepCopy() *RestrictedRoleDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(RestrictedRoleDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleDefinition) DeepCopyInto(out *RoleDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleDefinition.
func (in *RoleDefinition) DeepCopy() *RoleDefinition {
	if in == nil {
		return nil
	}
	out := new(RoleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleDefinitionList) DeepCopyInto(out *RoleDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RoleDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleDefinitionList.
func (in *RoleDefinitionList) DeepCopy() *RoleDefinitionList {
	if in == nil {
		return nil
	}
	out := new(RoleDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleDefinitionSpec) DeepCopyInto(out *RoleDefinitionSpec) {
	*out = *in
	if in.RestrictedAPIs != nil {
		in, out := &in.RestrictedAPIs, &out.RestrictedAPIs
		*out = make([]v1.APIGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RestrictedResources != nil {
		in, out := &in.RestrictedResources, &out.RestrictedResources
		*out = make([]v1.APIResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RestrictedVerbs != nil {
		in, out := &in.RestrictedVerbs, &out.RestrictedVerbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AggregationLabels != nil {
		in, out := &in.AggregationLabels, &out.AggregationLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AggregateFrom != nil {
		in, out := &in.AggregateFrom, &out.AggregateFrom
		*out = new(rbacv1.AggregationRule)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleDefinitionSpec.
func (in *RoleDefinitionSpec) DeepCopy() *RoleDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(RoleDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleDefinitionStatus) DeepCopyInto(out *RoleDefinitionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleDefinitionStatus.
func (in *RoleDefinitionStatus) DeepCopy() *RoleDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(RoleDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleLimits) DeepCopyInto(out *RoleLimits) {
	*out = *in
	if in.ForbiddenVerbs != nil {
		in, out := &in.ForbiddenVerbs, &out.ForbiddenVerbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenResources != nil {
		in, out := &in.ForbiddenResources, &out.ForbiddenResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenAPIGroups != nil {
		in, out := &in.ForbiddenAPIGroups, &out.ForbiddenAPIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenResourceVerbs != nil {
		in, out := &in.ForbiddenResourceVerbs, &out.ForbiddenResourceVerbs
		*out = make([]ResourceVerbRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaxRulesPerRole != nil {
		in, out := &in.MaxRulesPerRole, &out.MaxRulesPerRole
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleLimits.
func (in *RoleLimits) DeepCopy() *RoleLimits {
	if in == nil {
		return nil
	}
	out := new(RoleLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleRefLimits) DeepCopyInto(out *RoleRefLimits) {
	*out = *in
	if in.AllowedRoleRefs != nil {
		in, out := &in.AllowedRoleRefs, &out.AllowedRoleRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedRoleRefSelector != nil {
		in, out := &in.AllowedRoleRefSelector, &out.AllowedRoleRefSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ForbiddenRoleRefs != nil {
		in, out := &in.ForbiddenRoleRefs, &out.ForbiddenRoleRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenRoleRefSelector != nil {
		in, out := &in.ForbiddenRoleRefSelector, &out.ForbiddenRoleRefSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleRefLimits.
func (in *RoleRefLimits) DeepCopy() *RoleRefLimits {
	if in == nil {
		return nil
	}
	out := new(RoleRefLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SACreationConfig) DeepCopyInto(out *SACreationConfig) {
	*out = *in
	if in.AllowedCreationNamespaceSelector != nil {
		in, out := &in.AllowedCreationNamespaceSelector, &out.AllowedCreationNamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedCreationNamespaces != nil {
		in, out := &in.AllowedCreationNamespaces, &out.AllowedCreationNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutomountServiceAccountToken != nil {
		in, out := &in.AutomountServiceAccountToken, &out.AutomountServiceAccountToken
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SACreationConfig.
func (in *SACreationConfig) DeepCopy() *SACreationConfig {
	if in == nil {
		return nil
	}
	out := new(SACreationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SARef) DeepCopyInto(out *SARef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SARef.
func (in *SARef) DeepCopy() *SARef {
	if in == nil {
		return nil
	}
	out := new(SARef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountLimits) DeepCopyInto(out *ServiceAccountLimits) {
	*out = *in
	if in.AllowedNamespaceSelector != nil {
		in, out := &in.AllowedNamespaceSelector, &out.AllowedNamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ForbiddenNamespaces != nil {
		in, out := &in.ForbiddenNamespaces, &out.ForbiddenNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenNamespacePrefixes != nil {
		in, out := &in.ForbiddenNamespacePrefixes, &out.ForbiddenNamespacePrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Creation != nil {
		in, out := &in.Creation, &out.Creation
		*out = new(SACreationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountLimits.
func (in *ServiceAccountLimits) DeepCopy() *ServiceAccountLimits {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectLimits) DeepCopyInto(out *SubjectLimits) {
	*out = *in
	if in.AllowedKinds != nil {
		in, out := &in.AllowedKinds, &out.AllowedKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenKinds != nil {
		in, out := &in.ForbiddenKinds, &out.ForbiddenKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UserLimits != nil {
		in, out := &in.UserLimits, &out.UserLimits
		*out = new(NameMatchLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupLimits != nil {
		in, out := &in.GroupLimits, &out.GroupLimits
		*out = new(NameMatchLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccountLimits != nil {
		in, out := &in.ServiceAccountLimits, &out.ServiceAccountLimits
		*out = new(ServiceAccountLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectLimits.
func (in *SubjectLimits) DeepCopy() *SubjectLimits {
	if in == nil {
		return nil
	}
	out := new(SubjectLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedSelector) DeepCopyInto(out *UnifiedSelector) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Suffixes != nil {
		in, out := &in.Suffixes, &out.Suffixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedSelector.
func (in *UnifiedSelector) DeepCopy() *UnifiedSelector {
	if in == nil {
		return nil
	}
	out := new(UnifiedSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookAuthorizer) DeepCopyInto(out *WebhookAuthorizer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookAuthorizer.
func (in *WebhookAuthorizer) DeepCopy() *WebhookAuthorizer {
	if in == nil {
		return nil
	}
	out := new(WebhookAuthorizer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookAuthorizer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookAuthorizerList) DeepCopyInto(out *WebhookAuthorizerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebhookAuthorizer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookAuthorizerList.
func (in *WebhookAuthorizerList) DeepCopy() *WebhookAuthorizerList {
	if in == nil {
		return nil
	}
	out := new(WebhookAuthorizerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookAuthorizerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookAuthorizerSpec) DeepCopyInto(out *WebhookAuthorizerSpec) {
	*out = *in
	if in.ResourceRules != nil {
		in, out := &in.ResourceRules, &out.ResourceRules
		*out = make([]authorizationv1.ResourceRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NonResourceRules != nil {
		in, out := &in.NonResourceRules, &out.NonResourceRules
		*out = make([]authorizationv1.NonResourceRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowedPrincipals != nil {
		in, out := &in.AllowedPrincipals, &out.AllowedPrincipals
		*out = make([]Principal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeniedPrincipals != nil {
		in, out := &in.DeniedPrincipals, &out.DeniedPrincipals
		*out = make([]Principal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookAuthorizerSpec.
func (in *WebhookAuthorizerSpec) DeepCopy() *WebhookAuthorizerSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookAuthorizerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookAuthorizerStatus) DeepCopyInto(out *WebhookAuthorizerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookAuthorizerStatus.
func (in *WebhookAuthorizerStatus) DeepCopy() *WebhookAuthorizerStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookAuthorizerStatus)
	in.DeepCopyInto(out)
	return out
}
